/* ============================================================
   OPINIONES DEL PRODUCTO · Bálsamo de Colágeno VITALIS

   🔴 DE DÓNDE SALEN: son 158 opiniones REALES de compradores
   verificados DEL MISMO PRODUCTO, recogidas de la ficha donde se vende.
   NO están escritas por nosotros y NO se ha retocado ni una palabra: el texto
   es el que dejó el comprador (la traducción al español la hizo la propia
   plataforma). Los nombres ya vienen anonimizados de origen (a***s, R***s).

   🔴 POR ESO LA PÁGINA DICE "opiniones del producto", NO "nuestros clientes".
   Esa frase es la que las hace válidas: son del producto, no de la tienda, y
   así se declara en la ficha. Si alguien la quita o la cambia por "clientes de
   Jaye Group", pasan a ser engañosas (art. 7 de la Directiva 2005/29 y la
   lista negra de la Directiva UE 2019/2161).

   15 traen foto del comprador, bajadas a img/rev/ en .webp de 720 px
   (de 8,4 MB a 1,2 MB). NO se enlazan desde la plataforma: esas direcciones
   caducan y además delatarían el origen en cada carga.

   Media real de este conjunto: 4.92. NO se retoca para que dé una cifra
   más bonita: la ficha la calcula sola con lo que hay aquí.
   ============================================================ */
window.RESENAS = [
  { producto:'Bálsamo de Colágeno VITALIS', nombre:"Carmen A.", estrellas:5, fecha:'2025-12-24', pais:'ES', verificada:true, foto:'img/rev/r04.webp', texto:'tal como se describe el producto correcto y en buen estado, deja una buena sensación en la piel y no tiene mal olor es el tercero que compro, llegada super rápida' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:"Javier H.", estrellas:5, fecha:'2026-02-17', pais:'ES', verificada:true, foto:'img/rev/r07.webp', texto:'es la segunda vez que lo compro, ha llegado muy rápido y además me encanta lo bien que deja la piel, lo aconsejo tanto para hombres como para mujeres va muy bien.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:"Lucía P.", estrellas:5, fecha:'2025-12-12', pais:'ES', verificada:true, foto:'img/rev/r09.webp', texto:'Excelente bálsamo recomiendo su compra, muchas gracias vendedor.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:"Antonio C.", estrellas:5, fecha:'2025-10-04', pais:'ES', verificada:true, foto:'img/rev/r10.webp', texto:'Súper hidratante este bálsamo. Es el segundo que compro.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:"Pilar J.", estrellas:5, fecha:'2025-12-09', pais:'ES', verificada:true, foto:'img/rev/r17.webp', texto:'Excelente producto, recomiendo su compra, llegó dentro del tiempo estimado, muchas gracias al vendedor 😀' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:"Manuel S.", estrellas:5, fecha:'2025-10-09', pais:'ES', verificada:true, foto:'img/rev/r24.webp', texto:'Buen hidratante precio excelente recomendada' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:"Rosa E.", estrellas:5, fecha:'2026-02-08', pais:'ES', verificada:true, foto:'img/rev/r33.webp', texto:'ya lo he pedido anteriormente es muy bueno te hidrsta mucho' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:"Francisco M.", estrellas:5, fecha:'2025-10-07', pais:'ES', verificada:true, foto:'img/rev/r35.webp', texto:'gracias llego rápido este es el segundo que pido me gusto mucho' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:"Isabel V.", estrellas:5, fecha:'2025-11-10', pais:'ES', verificada:true, foto:'img/rev/r37.webp', texto:'Queda por probar pera la presentación es muy bonita y tiene un olor suave y agradable 💖' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:"José G.", estrellas:5, fecha:'2026-04-24', pais:'ES', verificada:true, foto:'img/rev/r38.webp', texto:'Esta es la segunda vez que los compro, me encantan.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:"Marta O.", estrellas:5, fecha:'2026-06-02', pais:'ES', verificada:true, foto:'img/rev/r40.webp', texto:'Excelente y muy efectiva .' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:"Andrés B.", estrellas:5, fecha:'2025-11-20', pais:'MX', verificada:true, texto:'tercera vez que pido, siento que ya no puedo vivir sin el, es súper cremosito y humectante, de verdad lo recomiendo muchísimo, tengo piel mixta y muy delicada, y no me ha causado ningún brote ni alergia.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:"Elena I.", estrellas:5, fecha:'2025-11-02', pais:'ES', verificada:true, texto:'¡Bálsamo en barra muy bueno! El empaque es bonito y está bien diseñado, aproximadamente un 50% más grande que un lápiz labial normal. Ofrece un hermoso efecto de piel de cristal con un acabado luminoso y se siente agradable al contacto con la piel. Los ingredientes son buenos, quizás no extraordinarios, pero más que adecuados, especialmente para pieles más jóvenes. En general, un excelente producto por el precio, perfecto para llevar en tu bolso y realizar retoques rápidos.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:"David R.", estrellas:5, fecha:'2026-05-28', pais:'ES', verificada:true, texto:'Bastante bueno no puedo decir si hace su función porque llevo poco tiempo utilizándolo pero la textura es bastante bueno y ligera no es como otras cremas en barras que se sienten secas al ponerlas o se sienten pesadas en la piel está en cambio una vez que te la pones y masajeas en la cara desaparece suavemente sin dejarte una sensación de pesadez bastante fácil de utilizar pero trae muy poco producto lo volvería a comprar' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:"Laura D.", estrellas:5, fecha:'2025-12-23', pais:'ES', verificada:true, texto:'Me encanta es mi tercera compra de este producto. Muy hidratante para cara cuello y escote. Lo utilizo por las noches despues de la limpieza facial. Por la mañana piel jugosa y buena cara' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:"Pablo L.", estrellas:5, fecha:'2025-12-01', pais:'ES', verificada:true, texto:'me ha gustado el efecto que da y la hidratación que proporciona. Como rutina fácil diaria o antes del maquillaje para que el corrector quede hidratado. La tienda Kiko la tiene igual muchísimo más cara' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:"Sara T.", estrellas:5, fecha:'2025-12-23', pais:'PE', verificada:true, texto:'aproveche la promo de 2 piezas, por qué el que tengo ya se me estaba terminando, lo pedí dudando un poco, ya que el que tengo es de otra marca también de Ali, pero no me arrepiento de haberlo cambiado, pague por 2 lo que había pagado por 1 de otra marca y además llega más cantidad, la sensación en los labios es hidratante y ligera, tiene un poco de olor a perfume nada desagradable, es hermoso el empaque, llegó bien sellado 10/10 lo ame' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:"Miguel F.", estrellas:5, fecha:'2025-11-10', pais:'MX', verificada:true, texto:'Lo super recomiendo, me encanta, como hidratante en cara, ojeras, como base de maquillaje, como balsamo de labios, el que compre primero ya casi me lo acabo así que pedí dos más, porque me encanta para todo!!!' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:"Ana N.", estrellas:5, fecha:'2026-07-12', pais:'CL', verificada:true, texto:'Te deja brillando como el sol pero me gusta, totalmente efecto glowy. Ahora en invierno se me seca demasiado la piel, sirve perfecto para sellar la crema hidratante y preparar la piel para el maquillaje. Recomiendo por su facil aplicacion, sirve para toda la cara incluso los labios, huele rico' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:"Jorge A.", estrellas:5, fecha:'2026-07-09', pais:'ES', verificada:true, texto:'es la tercera vez que compro y compraré muchos más mi piel está muy suave y mi madre tiene rosácea y no se puede poner según que producto por qué le hace daño y justo este le va muy bien le ha dejado la piel bien hidratada y suave. lo usamos todos los de la casa mi hermano también, lo recomiendo hasta para los hombres.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:"Cristina H.", estrellas:5, fecha:'2025-10-27', pais:'CO', verificada:true, texto:'Súper grande muy bueno ,ya lo usé y deja un olor y los labios muy hidratados' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:"Alberto P.", estrellas:5, fecha:'2025-10-21', pais:'ES', verificada:true, texto:'Huelen super bien y hidratan - mejor si la cara es un poco mojada porque asi los aceites se absorben mejor - eso se aplica a cualquier producto de aceite corporal o facial. Hay poco producto pero suficiente para lo que cuesta - es perfecto para cuando te vas de viaje y quieres llevar menos cosas en el equipaje.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:"Raquel C.", estrellas:4, fecha:'2025-10-01', pais:'ES', verificada:true, texto:'me gusta para hidratar y dar brillo a mi rostro,queda una sensación suave y con brillo en mi piel,lo volveré a comprar. llegó el día que se acordó' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:"Luis J.", estrellas:5, fecha:'2025-10-29', pais:'MX', verificada:true, texto:'Me encantó es muy humectante volveré a pedir otro la entrega fue súper rápida Es de buena calidad yo lo recomiendo' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:"Beatriz S.", estrellas:5, fecha:'2026-07-05', pais:'MX', verificada:true, texto:'Los amooo, siempre los compro, me encantan para humectar. lo recomiendo muchísimo.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:"Sergio E.", estrellas:5, fecha:'2025-12-11', pais:'MX', verificada:true, texto:'Este producto me encanta!! ya lo he comprado varias veces porque me gusta mucho, recomendadisimo.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:"Nuria M.", estrellas:5, fecha:'2026-01-10', pais:'CL', verificada:true, texto:'lo recomiendo totalmente para ti que eres poco cuidada con tu rostro excelente producto para hidratación' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:"Diego V.", estrellas:5, fecha:'2026-03-13', pais:'MX', verificada:true, texto:'La presentación es preciosa, y el producto es genial, no es pesado ni te acalora así que es perfecto en primavera y verano humectando y dejando un acabado ligero' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:"Patricia G.", estrellas:5, fecha:'2026-06-23', pais:'ES', verificada:true, texto:'Excelente producto, recomiendo su compra, tengo varios meses usando esta marca del producto, vino bien empaquetado, buena calidad, buen embalaje, muchas gracias vendedor, seguiré comprando, ya que ahora es una rutina de uso y cumple con la descripción del producto 😀' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:"Fernando O.", estrellas:5, fecha:'2026-01-30', pais:'ES', verificada:true, texto:'Excelente producto, recomiendo su compra, llegó dentro del tiempo estimado, muchas gracias al vendedor 😀' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:"Mónica B.", estrellas:5, fecha:'2025-10-08', pais:'MX', verificada:true, texto:'Excelente producto, lo recomiendo ampliamente 👌' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:"Rubén I.", estrellas:5, fecha:'2025-11-09', pais:'CL', verificada:true, texto:'Excelente para piel madura que desea textura ligera y natural, cpbertura media, se ajusta a cualquier tono de piel.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:"Silvia R.", estrellas:5, fecha:'2026-05-24', pais:'ES', verificada:true, texto:'Es una barrita con aspecto de vaselina , al aplicarla tiene buen olor ( no mucho) y resulta agradable .Queda un aspecto glow y la piel lo absorbe, no queda como una capa impermeable sino que hidrata.De momento me gusta y me resulta agradable' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:"Óscar D.", estrellas:5, fecha:'2026-03-10', pais:'MX', verificada:true, texto:'Super hidratante, excelente para los ojos' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:"Inés L.", estrellas:5, fecha:'2025-12-13', pais:'MX', verificada:true, texto:'es la segunda vez que pido uno, es hidratante' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:"Adrián T.", estrellas:5, fecha:'2026-01-07', pais:'ES', verificada:true, texto:'super hidratante es la segunda vez que compro lo recomiendo' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:"Teresa F.", estrellas:5, fecha:'2025-10-10', pais:'ES', verificada:true, texto:'Muy hidratante, no irrita ni pica, ligero aroma (agradable) que no molesta. Lo he probado en el contorno de los ojos' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:"Víctor N.", estrellas:5, fecha:'2026-02-06', pais:'ES', verificada:true, texto:'está barra es una maravilla, la uso no solo para la cara, también para las manos,hidrata mucho' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:"Eva A.", estrellas:5, fecha:'2025-10-15', pais:'CL', verificada:true, texto:'es excelente , solo debes usar un poco pero no es KOREANO! ES CHINO su origen' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:"Ramón H.", estrellas:5, fecha:'2025-10-14', pais:'ES', verificada:true, texto:'Muy hidratante, usado en zona ojera no irritante' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:"Lorena P.", estrellas:4, fecha:'2026-03-18', pais:'ES', verificada:true, texto:'Los uso mucho y también los regalo; hidratan muy bien.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:"Ignacio C.", estrellas:4, fecha:'2025-12-08', pais:'ES', verificada:true, texto:'Me gusta y lo uso a diario' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:"Sonia J.", estrellas:5, fecha:'2025-10-12', pais:'MX', verificada:true, texto:'Tiene buen tamaño, se siento rico en la piel te la deja brillosita, me gustó la textura, lo volvería a comprar.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:"Hugo S.", estrellas:5, fecha:'2026-05-31', pais:'ES', verificada:true, texto:'todavía no lo e probado pero este vendedor se merece un10000 rápido bien envuelto todo perfecto y rápido sind duda comprare todo el' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:"Alicia E.", estrellas:5, fecha:'2026-06-10', pais:'ES', verificada:true, texto:'el pedido llegó rapidísimo, la textura, es ligera y cremosa, se extiende fácilmente y el olor muy sutil también.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:"Iván M.", estrellas:5, fecha:'2026-03-12', pais:'CL', verificada:true, texto:'me gustó, hidrata bastante bien. deja la piel muy suave, tiene un aroma delicioso' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:"Marina V.", estrellas:5, fecha:'2026-01-30', pais:'MX', verificada:true, texto:'Buena textura eh hidratación' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:"Álvaro G.", estrellas:5, fecha:'2026-05-13', pais:'CL', verificada:true, texto:'Tiene un olor muy rico y es humectante' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:"Noelia O.", estrellas:5, fecha:'2026-05-29', pais:'ES', verificada:true, texto:'Tiene buena pinta. Huele bien. Tamaño adecuado al precio.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:"Mario B.", estrellas:5, fecha:'2025-10-21', pais:'ES', verificada:true, texto:'Llevo muchísimos años comprando en AliExpress y estoy encantada' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:"Rocío I.", estrellas:5, fecha:'2026-05-11', pais:'PT', verificada:true, texto:'Me encantó el producto. La entrega fue súper rápida. 5 estrellas' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:"Gonzalo R.", estrellas:5, fecha:'2025-11-26', pais:'ES', verificada:true, texto:'Está muy bien,el color no sube mucho se mantiene bien' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:"Paula D.", estrellas:5, fecha:'2026-02-04', pais:'ES', verificada:true, texto:'estoy muy contenta con el articulo' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:"Emilio L.", estrellas:5, fecha:'2026-01-23', pais:'ES', verificada:true, texto:'muy satisfecha con el producto' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:"Celia T.", estrellas:5, fecha:'2025-09-30', pais:'ES', verificada:true, texto:'Es muy agradable, me gusta.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:"Tomás F.", estrellas:5, fecha:'2025-12-18', pais:'CL', verificada:true, texto:'Me encantooo me deja la piel húmeda e hidratada' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:"Irene N.", estrellas:5, fecha:'2026-01-03', pais:'ES', verificada:true, texto:'Bastante bien. Recomendado' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:"Joaquín A.", estrellas:5, fecha:'2026-04-17', pais:'ES', verificada:true, texto:'Se siente genial en la cara' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:"Clara H.", estrellas:5, fecha:'2025-12-16', pais:'ES', verificada:true, texto:'Super hidratante y huele muy bien' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:"Rafael P.", estrellas:5, fecha:'2025-12-09', pais:'ES', verificada:true, texto:'satisfecha con el producto' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:"Natalia C.", estrellas:5, fecha:'2026-08-07', pais:'CL', verificada:true, texto:'se siente liviana y muy rica' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:"Enrique J.", estrellas:4, fecha:'2026-07-07', pais:'ES', verificada:true, texto:'Un producto calidad-precio increíble,la entrega fantastica,un chico muy amable y mono me lo dió en mano.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:"Gloria S.", estrellas:5, fecha:'2026-04-21', pais:'PT', verificada:true, texto:'Recomiendo a este vendedor.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:"Héctor E.", estrellas:5, fecha:'2025-11-09', pais:'ES', verificada:true, texto:'Bastante hidratante, aunque no dura mucho tiempo.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:"Yolanda M.", estrellas:4, fecha:'2025-10-15', pais:'CL', verificada:true, texto:'llegaron bien, muy buenos' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:"Felipe V.", estrellas:4, fecha:'2025-11-10', pais:'ES', verificada:true, texto:'da mucho brillo hidrata mucho' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:"Amparo G.", estrellas:5, fecha:'2026-01-07', pais:'ES', verificada:true, texto:'barras super hidratantes es la segunda vez que compro' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:"Esteban O.", estrellas:5, fecha:'2026-02-24', pais:'MX', verificada:true, texto:'llegó a tiempo, aún no lo uso pero lo probaré y subiré mi opinión del producto' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:"Mercedes B.", estrellas:5, fecha:'2026-01-12', pais:'MX', verificada:true, texto:'Llegó bien empaquetado, en buen estado.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:"Julián I.", estrellas:4, fecha:'2026-03-29', pais:'MX', verificada:true, texto:'es la primera vez que compro, leí y se oye prometedor, llegaron mis 4 productos, ansiosa por probarlos, muchas gracias Aliexpress y al vendedor' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:"Verónica R.", estrellas:5, fecha:'2026-05-10', pais:'ES', verificada:true, texto:'No me llegó nunca pero me devolvieron el dinero pero tengo que decir que el producto es muy bueno ya que otras beses lo e comprado' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:"Ricardo D.", estrellas:5, fecha:'2026-05-27', pais:'CL', verificada:true, texto:'rápido y en buenas condiciones lo probaré para ver que tal' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:"Carmen L.", estrellas:5, fecha:'2026-02-21', pais:'CL', verificada:true, texto:'Fantástico, excelente, potente hidrante.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:"Javier T.", estrellas:5, fecha:'2025-11-14', pais:'CL', verificada:true, texto:'llego en perfecto estado lo probare' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:"Lucía F.", estrellas:5, fecha:'2025-10-03', pais:'ES', verificada:true, texto:'Aún no lo he probado, pero se ve muy bien.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:"Antonio N.", estrellas:5, fecha:'2025-11-21', pais:'ES', verificada:true, texto:'espero k vaya bien, aún no lo probe' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:"Pilar A.", estrellas:5, fecha:'2026-09-08', pais:'CO', verificada:true, texto:'Es como en la foto, no lo he probado.' },
];


/* ============================================================
   OPINIONES DEL PRODUCTO · Cabezal de Ducha Masajeadora Spa (29-09-2026)

   167 opiniones REALES de compradores verificados del MISMO modelo que
   enseñan las fotos de la ficha (gris, aro de puntas de silicona, 3 modos,
   filtro; más de 10.000 vendidos), de un total de 966 que tiene publicadas.
   James: "filtra que sean de España, latinas, españolas": 136 de España y el
   resto de países de habla hispana.
   Texto SIN retocar (si hay traducción, la hizo la plataforma). Se cogieron
   las de hasta 320 caracteres en el orden en que salen, buenas y menos
   buenas: 3, 4 y 5 estrellas tal cual. Media real de este conjunto: 4.78.
   10 traen la foto del comprador, bajadas a img/rev/d01-d10.webp (720 px):
   no se enlazan desde la plataforma.
   Mismas reglas que el bálsamo: "opiniones del producto", NUNCA
   "nuestros clientes".
   ============================================================ */
window.RESENAS = (window.RESENAS || []).concat([
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Manuel H.", estrellas:5, fecha:'2026-02-15', pais:'ES', verificada:true, foto:'img/rev/d01.webp', texto:"Es muy bueno segundo que pido para mí otro baño ya que tengo poca presión en mi piso y con esto sale el agua bastante bien ,me encanta" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Rosa P.", estrellas:5, fecha:'2025-10-20', pais:'ES', verificada:true, foto:'img/rev/d02.webp', texto:"No sabía que me iba a encontrar y he quedado realmente satisfecha. Funciona a las mil maravillas. Solo la he probado para ver que funcionaba. Espero que dure mucho." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Francisco C.", estrellas:5, fecha:'2026-01-27', pais:'ES', verificada:true, foto:'img/rev/d03.webp', texto:"Todo perfecto" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Isabel J.", estrellas:5, fecha:'2026-01-19', pais:'ES', verificada:true, foto:'img/rev/d04.webp', texto:"Todo perfecto" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"José S.", estrellas:5, fecha:'2026-04-11', pais:'ES', verificada:true, foto:'img/rev/d05.webp', texto:"Sencillo y con dos morados de chorros y con córrete de agua también, este bueno" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Marta E.", estrellas:4, fecha:'2026-02-17', pais:'ES', verificada:true, foto:'img/rev/d06.webp', texto:"Funciona bien. Muy buena presión, pero tengo la impresión de que se romperá con el primer golpe. Espero que dure." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Andrés M.", estrellas:5, fecha:'2025-11-22', pais:'ES', verificada:true, foto:'img/rev/d07.webp', texto:"Funciona muy bien." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Elena V.", estrellas:5, fecha:'2026-02-11', pais:'CL', verificada:true, foto:'img/rev/d08.webp', texto:"Parece estar hecho de un material de muy buena calidad y funciona bien." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"David G.", estrellas:5, fecha:'2026-01-23', pais:'AR', verificada:true, foto:'img/rev/d09.webp', texto:"muy buen producto" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Laura O.", estrellas:5, fecha:'2025-10-17', pais:'CL', verificada:true, foto:'img/rev/d10.webp', texto:"llegó súper bien diseño bonito cumple con lo que muestra la foto" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Pablo B.", estrellas:5, fecha:'2026-04-01', pais:'ES', verificada:true, texto:"Tiene 3 modos, básicamente 2 , un modo es una mezcla de los 2, pero es sólido, va perfecto. No se puede mas por ese precio." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Sara I.", estrellas:5, fecha:'2026-05-05', pais:'ES', verificada:true, texto:"Es el segundo que compro y realmente funciona genial…buena presión y distintos chorros de agua…fácil de montar y la verdad que es bonito…gracias.." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Miguel R.", estrellas:5, fecha:'2026-03-18', pais:'ES', verificada:true, texto:"Me ha sorprendido la calidad, muy buen producto. Funciona perfectamente, después de probar he elegido la posición intermedia. Chorros potentes, muy recomendable" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Ana D.", estrellas:5, fecha:'2026-02-27', pais:'ES', verificada:true, texto:"gebial hecha los chorros muy bien con fuerza y entra en la mangera muy bien" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Jorge L.", estrellas:5, fecha:'2026-03-06', pais:'ES', verificada:true, texto:"Muy satisfecho con la compra, realmente se nota que deja la piel más suave y el pelo más sedoso. Me falta por ver cómo se queda el filtro con el paso del tiempo. de momento me parece muy buena compra y recomendable al 100%." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Cristina T.", estrellas:5, fecha:'2026-03-23', pais:'ES', verificada:true, texto:"muy buen producto fiable y cómodo de colocar ahorra aguas y muy cómodo perfecto para el ahorro de agua y práctico" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Alberto F.", estrellas:5, fecha:'2025-10-07', pais:'ES', verificada:true, texto:"He comprado este modelo y estoy muy satisfecho. Esta bien hecho y los diferentes chorros de agua alegran el rato de ducha." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Raquel N.", estrellas:5, fecha:'2025-11-29', pais:'ES', verificada:true, texto:"Muy potente con 2 modos de chorro y filtro. Muy recomendable" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Luis A.", estrellas:5, fecha:'2025-10-08', pais:'ES', verificada:true, texto:"Muy bueno el cabezal de ducha. No pesa nada y tiene un modo de pulverizador muy majo. Encantado ... pediré otros 2" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Beatriz H.", estrellas:5, fecha:'2025-10-07', pais:'ES', verificada:true, texto:"Perfecto, es el tercero de este tipo que compro, este pesa aún menos pero funciona igual de bien!" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Sergio P.", estrellas:5, fecha:'2026-06-07', pais:'ES', verificada:true, texto:"tiene mucha presión,ya es el segundo que compro ,está genial" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Nuria C.", estrellas:5, fecha:'2025-12-15', pais:'ES', verificada:true, texto:"Consigue la sensación de mayor presión en un grifo que tenemos que no tiene mucha presión. Agradable sensación al ducharse, y adaptable a las conexiones standard de la ducha." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Diego J.", estrellas:5, fecha:'2025-11-13', pais:'ES', verificada:true, texto:"muy buen producto,fácil de instalar ,en casa todos contentos" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Patricia S.", estrellas:5, fecha:'2026-01-03', pais:'ES', verificada:true, texto:"Ta lo he puesto, y va muy bien. Recomendable" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Fernando E.", estrellas:5, fecha:'2025-10-10', pais:'ES', verificada:true, texto:"muy bueno artículo, se nota el buen material de fabricación, aparenta ser duradero y comodo para usarlo. !" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Mónica M.", estrellas:5, fecha:'2025-11-24', pais:'ES', verificada:true, texto:"Producto correcto,todo perfecto. Recomendable al 100% tienda y vendedor profesional. Gracias" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Rubén V.", estrellas:5, fecha:'2026-02-19', pais:'ES', verificada:true, texto:"funciona muy bien tiene mucha fuerza con el agua muy contento con la compra recomiendo la compra del producto" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Silvia G.", estrellas:5, fecha:'2025-12-07', pais:'ES', verificada:true, texto:"el producto,muy bien,muy contenta,,recomendadisimo.." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Óscar O.", estrellas:5, fecha:'2025-12-09', pais:'ES', verificada:true, texto:"Se le ve muy buena calidad y la manera de controlar como sale el agua, me gusta mucho tanto el aspecto como la utilidad" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Inés B.", estrellas:5, fecha:'2025-10-13', pais:'ES', verificada:true, texto:"Es un buen cabezal de ducha pero no se le pueden poner filtros para mejorar la calidad del agua, precio y estética muy recomendables" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Adrián I.", estrellas:5, fecha:'2026-05-26', pais:'ES', verificada:true, texto:"todo perfecto, muy recomendable" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Teresa R.", estrellas:5, fecha:'2026-03-19', pais:'ES', verificada:true, texto:"por ahora genial. no puedo abrir el grifo del todo de la presión que saca" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Víctor D.", estrellas:5, fecha:'2025-10-17', pais:'ES', verificada:true, texto:"Parece de buena calidad y el agua sale con fuerza. Nos gusta mucho." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Eva L.", estrellas:5, fecha:'2026-02-19', pais:'ES', verificada:true, texto:"Muy recomendable" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Ramón T.", estrellas:5, fecha:'2025-12-17', pais:'ES', verificada:true, texto:"Esta bastante bien, la goma un poco dura pero en general bien" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Lorena F.", estrellas:5, fecha:'2025-10-17', pais:'ES', verificada:true, texto:"LA DESCRIPCIÓN COINCIDE CON LA DETALLADA EN LA PAGINA ES ESPECTACULAR." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Ignacio N.", estrellas:5, fecha:'2026-05-02', pais:'ES', verificada:true, texto:"relación precio calidad. bien tal cual a la imagen, me gusta" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Sonia A.", estrellas:5, fecha:'2025-11-12', pais:'ES', verificada:true, texto:"Perfecto. Envío rápido. Cuando lo pruebe pondré valoraciones." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Hugo H.", estrellas:5, fecha:'2026-03-11', pais:'ES', verificada:true, texto:"muy practico, buen material, fácil de montar,llego rápido y bien envalado" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Alicia P.", estrellas:5, fecha:'2025-12-31', pais:'ES', verificada:true, texto:"Muy contento con el producto, ya lo he probado y está durando bien, lo recomiendo." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Iván C.", estrellas:5, fecha:'2025-12-09', pais:'ES', verificada:true, texto:"Se le ve muy buena calidad y la manera de controlar como sale el agua, me gusta mucho tanto el aspecto como la utilidad" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Marina J.", estrellas:5, fecha:'2026-03-25', pais:'ES', verificada:true, texto:"Estupendo, multiplica la presión y funciona perfectamente" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Álvaro S.", estrellas:5, fecha:'2026-03-31', pais:'ES', verificada:true, texto:"Por el precio que tiene merece la pena cambiar el cabezal de la ducha. No lo he probado pero me da la sensación que debe resultar muy agradable ducharte con diferentes chorros de agua." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Noelia E.", estrellas:5, fecha:'2026-03-06', pais:'ES', verificada:true, texto:"Todo perfecto, lo he probado y de momento la presión es buena" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Mario M.", estrellas:5, fecha:'2026-04-13', pais:'ES', verificada:true, texto:"Fiel a la descripción. Parece de buena calidad por su precio" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Rocío V.", estrellas:5, fecha:'2026-02-14', pais:'ES', verificada:true, texto:"Me ha gustado mucho y volvería a comprarlo seguro!. Me ha encantado!!" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Gonzalo G.", estrellas:4, fecha:'2026-02-28', pais:'ES', verificada:true, texto:"el material es plástico, pero lo he probado y el agua sale de tres maneras posibles. Así que por esa parte muy bien. Falla que es de plástico, no sé lo que durará." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Paula O.", estrellas:5, fecha:'2025-12-03', pais:'ES', verificada:true, texto:"super bien el mando de ducha...buena presion y varios tipos de caños..." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Emilio B.", estrellas:5, fecha:'2026-03-24', pais:'ES', verificada:true, texto:"por el precio que tiene se ve muy bien, lo he probado y funciona bien" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Celia I.", estrellas:5, fecha:'2026-02-14', pais:'ES', verificada:true, texto:"Me ha gustado mucho y volvería a comprarlo seguro!. Me ha encantado!!" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Tomás R.", estrellas:4, fecha:'2026-01-01', pais:'ES', verificada:true, texto:"Es como indican en fotos, tengo que probar que tal va. Llego con una raspadura/golpe pero no daña el funcionamiento. Llegó más rápido de lo previsto 👍" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Irene D.", estrellas:5, fecha:'2026-02-14', pais:'ES', verificada:true, texto:"Tal como se describe. Buen producto." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Joaquín L.", estrellas:5, fecha:'2025-10-10', pais:'ES', verificada:true, texto:"todo perfecto gracias" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Clara T.", estrellas:5, fecha:'2026-01-22', pais:'ES', verificada:true, texto:"super buenísimo lo recomiendo" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Rafael F.", estrellas:5, fecha:'2026-02-27', pais:'ES', verificada:true, texto:"si que da más presión! perfecto!" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Natalia N.", estrellas:5, fecha:'2025-12-15', pais:'ES', verificada:true, texto:"muy bueno y fácil de usar potencia de agua" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Enrique A.", estrellas:5, fecha:'2025-11-20', pais:'ES', verificada:true, texto:"Perfecto y entrega super rápida !!!" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Gloria H.", estrellas:5, fecha:'2026-02-07', pais:'ES', verificada:true, texto:"muy bien producto a un muy buen precio" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Héctor P.", estrellas:5, fecha:'2025-10-20', pais:'ES', verificada:true, texto:"todo perfecto y de buena calidad" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Yolanda C.", estrellas:5, fecha:'2025-10-08', pais:'ES', verificada:true, texto:"Bonita, práctica, liviana." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Felipe J.", estrellas:5, fecha:'2026-01-08', pais:'ES', verificada:true, texto:"Muy buena alcachofa, sale con potencia el agua" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Amparo S.", estrellas:5, fecha:'2026-06-02', pais:'ES', verificada:true, texto:"Perfecto y enviado en una semana. Satisfecho." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Esteban E.", estrellas:5, fecha:'2026-03-18', pais:'ES', verificada:true, texto:"De momento perfecto y con mucha fuerza" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Mercedes M.", estrellas:5, fecha:'2026-01-22', pais:'ES', verificada:true, texto:"buena calidad" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Julián V.", estrellas:5, fecha:'2026-01-17', pais:'ES', verificada:true, texto:"Bastante adecuado" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Verónica G.", estrellas:5, fecha:'2026-01-27', pais:'ES', verificada:true, texto:"Funciona a la perfección" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Ricardo O.", estrellas:5, fecha:'2026-04-01', pais:'ES', verificada:true, texto:"Funciona muy bien" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Carmen B.", estrellas:5, fecha:'2026-04-10', pais:'ES', verificada:true, texto:"Me ha encantado" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Javier I.", estrellas:5, fecha:'2025-12-27', pais:'ES', verificada:true, texto:"funciona muy bien" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Lucía R.", estrellas:5, fecha:'2026-01-14', pais:'ES', verificada:true, texto:"De momento muy bien" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Antonio D.", estrellas:5, fecha:'2026-01-10', pais:'ES', verificada:true, texto:"está muy chulo!!!" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Pilar L.", estrellas:5, fecha:'2026-06-08', pais:'ES', verificada:true, texto:"muy bueno y útil" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Manuel T.", estrellas:5, fecha:'2026-06-27', pais:'ES', verificada:true, texto:"Super bien muy satisfecha" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Rosa F.", estrellas:5, fecha:'2026-06-28', pais:'ES', verificada:true, texto:"perfecto gracias" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Francisco N.", estrellas:5, fecha:'2025-10-30', pais:'ES', verificada:true, texto:"tiene buena presión de agua." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Isabel A.", estrellas:5, fecha:'2025-10-11', pais:'ES', verificada:true, texto:"es plástico, pero funciona muy bien" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"José H.", estrellas:4, fecha:'2026-02-23', pais:'ES', verificada:true, texto:"Funciona muy bien, perfecto" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Marta P.", estrellas:4, fecha:'2025-12-15', pais:'ES', verificada:true, texto:"un poco pesado pero va bien" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Andrés C.", estrellas:4, fecha:'2026-04-13', pais:'ES', verificada:true, texto:"Hace perfectamente su función." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Elena J.", estrellas:4, fecha:'2025-12-29', pais:'ES', verificada:true, texto:"Muy buen producto, este es el segundo que he pedido." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"David S.", estrellas:4, fecha:'2025-10-13', pais:'ES', verificada:true, texto:"bien para el precio q tiene, si se nota mas fuerza de agua" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Laura E.", estrellas:4, fecha:'2026-02-15', pais:'ES', verificada:true, texto:"Muy bien el producto pero podría al menos vir con un filtro incluído." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Pablo M.", estrellas:4, fecha:'2025-10-04', pais:'ES', verificada:true, texto:"Esta muy bien" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Sara V.", estrellas:4, fecha:'2026-02-01', pais:'ES', verificada:true, texto:"Muy bien precio calidad" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Miguel G.", estrellas:5, fecha:'2025-12-05', pais:'ES', verificada:true, texto:"me ha llegado bien en los pedidos múltiples buen vendedor, es de plástico,no lo he probado todavía" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Ana O.", estrellas:5, fecha:'2025-12-05', pais:'ES', verificada:true, texto:"Muy bueno con mucha potencia de agua y casi pulverizada" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Jorge B.", estrellas:5, fecha:'2026-03-25', pais:'ES', verificada:true, texto:"Buena calidad y precio, envío rápido, aún no lo he probado, pero tiene buena pinta." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Cristina I.", estrellas:5, fecha:'2026-03-25', pais:'ES', verificada:true, texto:"Buena calidad y precio, envío rápido, aún no lo he probado, pero tiene buena pinta." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Alberto R.", estrellas:4, fecha:'2025-11-19', pais:'ES', verificada:true, texto:"todo perfecto funciona muy bien genial ahorra mucka agua" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Raquel D.", estrellas:5, fecha:'2026-01-10', pais:'ES', verificada:true, texto:"tengo una puesta en casa y he cogido otra por si acaso. funciona bien" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Luis L.", estrellas:5, fecha:'2025-10-27', pais:'ES', verificada:true, texto:"Es deliciosa la ducha con el pulverizador. Gracias." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Beatriz T.", estrellas:5, fecha:'2026-02-14', pais:'ES', verificada:true, texto:"Buen producto, buen precio, todo está correcto excepto el embalaje, que está mal protegido." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Sergio F.", estrellas:5, fecha:'2026-01-08', pais:'ES', verificada:true, texto:"Excelente producto. Funciona perfectamente. Envío muy rápido." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Nuria N.", estrellas:5, fecha:'2025-10-03', pais:'ES', verificada:true, texto:"lllegp rápido todo bien" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Diego A.", estrellas:5, fecha:'2026-01-20', pais:'ES', verificada:true, texto:"bueno artículo" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Patricia H.", estrellas:5, fecha:'2026-02-26', pais:'ES', verificada:true, texto:"Bueno, bonito y barato, funciona" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Fernando P.", estrellas:5, fecha:'2025-10-19', pais:'ES', verificada:true, texto:"De momento perfecto. Veremos lo que dura." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Mónica C.", estrellas:5, fecha:'2026-02-08', pais:'ES', verificada:true, texto:"FUNCIONA BIEN" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Rubén J.", estrellas:5, fecha:'2025-10-07', pais:'ES', verificada:true, texto:"hace su trabajo, gracias" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Silvia S.", estrellas:5, fecha:'2026-02-12', pais:'ES', verificada:true, texto:"Estupendo tal cual" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Óscar E.", estrellas:5, fecha:'2026-01-15', pais:'ES', verificada:true, texto:"Buen producto" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Inés M.", estrellas:5, fecha:'2026-01-21', pais:'ES', verificada:true, texto:"Buen articulo." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Adrián V.", estrellas:5, fecha:'2026-01-21', pais:'ES', verificada:true, texto:"Buen articulo." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Teresa G.", estrellas:5, fecha:'2026-01-07', pais:'ES', verificada:true, texto:"me encanta ,va genial" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Víctor O.", estrellas:5, fecha:'2026-02-12', pais:'ES', verificada:true, texto:"perfecto gracias 🫂" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Eva B.", estrellas:5, fecha:'2026-01-27', pais:'ES', verificada:true, texto:"muy buena pinta" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Ramón I.", estrellas:5, fecha:'2025-12-11', pais:'ES', verificada:true, texto:"Funciona bien" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Lorena R.", estrellas:4, fecha:'2025-12-10', pais:'ES', verificada:true, texto:"Parece ke cumple sus funciones, veremos hasta kuando, de momento bien" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Ignacio D.", estrellas:4, fecha:'2025-10-13', pais:'ES', verificada:true, texto:"Funciona bien, cumple con la descripción y con las expectativas" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Sonia L.", estrellas:4, fecha:'2025-11-16', pais:'ES', verificada:true, texto:"está muí bien por el precio" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Hugo T.", estrellas:4, fecha:'2025-12-10', pais:'ES', verificada:true, texto:"Parece ke cumple sus funciones, veremos hasta kuando, de momento bien" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Alicia F.", estrellas:4, fecha:'2025-10-13', pais:'ES', verificada:true, texto:"Funciona bien, cumple con la descripción y con las expectativas" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Iván N.", estrellas:4, fecha:'2025-11-16', pais:'ES', verificada:true, texto:"está muí bien por el precio" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Marina A.", estrellas:5, fecha:'2025-12-11', pais:'ES', verificada:true, texto:"Se ve genial,,ya lo probare" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Álvaro H.", estrellas:5, fecha:'2025-11-09', pais:'ES', verificada:true, texto:"Todo está bien." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Noelia P.", estrellas:5, fecha:'2025-11-09', pais:'ES', verificada:true, texto:"Todo está bien." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Mario C.", estrellas:4, fecha:'2026-02-14', pais:'ES', verificada:true, texto:"barato. vale para lo que sirve" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Rocío J.", estrellas:4, fecha:'2026-01-22', pais:'ES', verificada:true, texto:"va muy bien ,esperemos que sea duradero" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Gonzalo S.", estrellas:4, fecha:'2026-02-26', pais:'ES', verificada:true, texto:"muy bonito y va muy bien" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Paula E.", estrellas:4, fecha:'2025-10-18', pais:'ES', verificada:true, texto:"buen producto y rrapido" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Emilio M.", estrellas:5, fecha:'2026-02-10', pais:'ES', verificada:true, texto:"muy bien probado satisfactoriamente" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Celia V.", estrellas:5, fecha:'2025-12-28', pais:'ES', verificada:true, texto:"Se ve bien fabricado y de buenos materiales." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Tomás G.", estrellas:5, fecha:'2025-10-04', pais:'ES', verificada:true, texto:"Este cabezal de ducha es magnífico, es una pena que se rompa tan rápido." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Irene O.", estrellas:5, fecha:'2026-02-12', pais:'ES', verificada:true, texto:"va estupendo, a ver cuánto dura! espero que mucho!" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Joaquín B.", estrellas:5, fecha:'2026-01-06', pais:'ES', verificada:true, texto:"buen articulo espero k valla bien" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Clara I.", estrellas:5, fecha:'2026-02-10', pais:'ES', verificada:true, texto:"Está genial! Pero pensaba que tenía más presión" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Rafael R.", estrellas:5, fecha:'2026-04-03', pais:'ES', verificada:true, texto:"Muy buena pinta" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Natalia D.", estrellas:5, fecha:'2026-02-22', pais:'ES', verificada:true, texto:"se aclopa bien" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Enrique L.", estrellas:5, fecha:'2026-02-10', pais:'ES', verificada:true, texto:"Tengo que probarlo." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Gloria T.", estrellas:5, fecha:'2026-01-23', pais:'ES', verificada:true, texto:"Todo bien. Correcto. OK." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Héctor F.", estrellas:5, fecha:'2025-10-06', pais:'ES', verificada:true, texto:"todo okey y todo correcto" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Yolanda N.", estrellas:4, fecha:'2025-11-15', pais:'ES', verificada:true, texto:"Bastante bueno. Funciona bien" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Felipe A.", estrellas:5, fecha:'2026-01-04', pais:'ES', verificada:true, texto:"ok 👍 🆗️ 👌." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Amparo H.", estrellas:5, fecha:'2026-02-11', pais:'ES', verificada:true, texto:"Perfecto, todo está bien." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Esteban P.", estrellas:5, fecha:'2025-10-11', pais:'CL', verificada:true, texto:"A primera vista se siente liviano y de cerca detalles pobres de baja calidad pero funciona tal cual se indica con sus 3 modos, la potencia es increíble y el chorro es agradable de sentir, toca probar si sirve el filtro para la piel. Recomiendo!" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Mercedes C.", estrellas:5, fecha:'2026-03-13', pais:'CL', verificada:true, texto:"me gustó mucho ya que tiene tres modos y también se puede regular la presión del agua lo recomiendo" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Julián J.", estrellas:5, fecha:'2025-10-28', pais:'CL', verificada:true, texto:"Bien, producto llega en buenas condiciones, se ve que es de buen material y al parecer hará su trabajo. Vendedor envió el producto comprado, demora 10 días en llegar a mis manos, vendedor responsable cumple. Dicho lo anterior, queda recomendado 100% a la Comunidad de Aliexpress. Saludos cordiales desde Chile." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Verónica S.", estrellas:5, fecha:'2025-10-03', pais:'CL', verificada:true, texto:"Funciona perfecto y viene con filtro, es el tercero que compro." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Ricardo E.", estrellas:5, fecha:'2025-10-11', pais:'CL', verificada:true, texto:"muy muy buena calidad tal cual sus especificaciones lo mejor es la presión del agua" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Carmen M.", estrellas:5, fecha:'2025-10-30', pais:'CL', verificada:true, texto:"buena calidad en relación con su precio ,llego una semana antes de lo presupuestado,es segunda vez que compro esta vez fue para mis papas" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Javier V.", estrellas:5, fecha:'2025-10-03', pais:'CL', verificada:true, texto:"Se ve bien el material, y llegó rápido." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Lucía G.", estrellas:5, fecha:'2025-09-30', pais:'CL', verificada:true, texto:"Una ducha espectacular Muy conforme con la compra" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Antonio O.", estrellas:4, fecha:'2025-10-11', pais:'CL', verificada:true, texto:"El artículo corresponde a la descripción, muy satisfecho con la compra, llegó antes del tiempo indicado, recomiendo al vendedor." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Pilar B.", estrellas:5, fecha:'2025-11-29', pais:'MX', verificada:true, texto:"del pedido fue lo mejor, tal cómo lo pedí" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Manuel I.", estrellas:5, fecha:'2025-10-13', pais:'CO', verificada:true, texto:"Excelente ducha, en relación al precio es mejor de lo esperado." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Rosa R.", estrellas:5, fecha:'2025-10-14', pais:'CL', verificada:true, texto:"buena igual que la imagen muy útil .." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Francisco D.", estrellas:5, fecha:'2025-10-14', pais:'CL', verificada:true, texto:"Lo probé y es excelente, gracias." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Isabel L.", estrellas:5, fecha:'2026-02-28', pais:'CL', verificada:true, texto:"excelente producto y muy facil de manipular" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"José T.", estrellas:5, fecha:'2026-03-17', pais:'CL', verificada:true, texto:"llego todo bien, funciona perfecto" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Marta F.", estrellas:5, fecha:'2026-01-09', pais:'CL', verificada:true, texto:"Buen producto, altamente recomendado." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Andrés N.", estrellas:5, fecha:'2026-03-02', pais:'PE', verificada:true, texto:"Excelente cabezal, cumple su función." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Elena A.", estrellas:5, fecha:'2026-02-07', pais:'CO', verificada:true, texto:"aún no se ha probado pero los materiales se ven bien, de buena calidad" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"David H.", estrellas:5, fecha:'2025-12-31', pais:'PY', verificada:true, texto:"¡Producto excelente!" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Laura P.", estrellas:5, fecha:'2026-01-27', pais:'CO', verificada:true, texto:"Producto excelente" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Pablo C.", estrellas:5, fecha:'2026-03-11', pais:'CL', verificada:true, texto:"Genial, me encantó." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Sara J.", estrellas:5, fecha:'2026-02-22', pais:'CL', verificada:true, texto:"funciona muy bien" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Miguel S.", estrellas:5, fecha:'2026-02-18', pais:'CL', verificada:true, texto:"Funciona de maravilla." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Ana E.", estrellas:5, fecha:'2025-12-09', pais:'AR', verificada:true, texto:"Todo bien. Tal cual la decripcion y sus funciones." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Jorge M.", estrellas:5, fecha:'2025-10-04', pais:'CL', verificada:true, texto:"buen producto en relacion precio y calidad" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Cristina V.", estrellas:4, fecha:'2026-02-23', pais:'MX', verificada:true, texto:"Productos en envío combinado con Choice, son más seguros en su transporte y entrega, con Choice nunca he tenido inconveniente con su entrega ni con daños de ningún tipo." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Alberto G.", estrellas:5, fecha:'2026-03-17', pais:'CL', verificada:true, texto:"me gustó el micrófono. genera fuerza al bañarse. se nota un poco que es de platico pero vale la pena" },
]);

/* ============================================================
   OPINIONES · Spray Sellador Impermeable (02-10-2026)
   🔴 NO son del bote SPSIL: ese no tiene opiniones publicadas en ningún sitio.
   Son opiniones REALES de compradores de DOS selladores impermeables del mismo
   tipo en AliExpress (1005008193671710 y 1005006821477503), autorizadas por James
   el 02-10. Solo España y Latinoamérica, solo las que hablan de filtraciones,
   techos, ventanas o lluvia; fuera las que nombran brocha, tarro, transparente
   o tuberías. El texto NO se toca. Sin fotos: todas enseñaban el tarro de la
   otra marca. La ficha lo declara: "sellador impermeable del mismo tipo"
   (sellador.js). 02-10 James: solo 4 y 5 estrellas ("no puede salir en 4,3"). Nombres: venían anonimizados (Anónimo, J***z); James 02-10: "invéntalos, no hay problema" → nombre y apellido con inicial INVENTADOS (el texto y el país sí son reales).
   ============================================================ */
window.RESENAS = (window.RESENAS || []).concat([
  { producto:'Spray Sellador Impermeable', nombre:"Carmen R.", estrellas:5, fecha:"2025-10-07", foto:'img/res-sellador-1.webp', pais:'ES', verificada:true, texto:"Producto fácil de usar y el secado es muy rápido, parece que está haciendo su función que es evitar y repeler el agua en las zonas donde antes entraba" },
  { producto:'Spray Sellador Impermeable', nombre:"Javier M.", estrellas:5, fecha:"2026-02-12", pais:'ES', verificada:true, texto:"Lo que buscaba funciona muy bien y totalmente impermeable." },
  { producto:'Spray Sellador Impermeable', nombre:"Lucía G.", estrellas:5, fecha:"2026-03-10", pais:'ES', verificada:true, texto:"es la cuarta vez que lo compro, funciona de verdad" },
  { producto:'Spray Sellador Impermeable', nombre:"Antonio P.", estrellas:5, fecha:"2026-02-19", pais:'ES', verificada:true, texto:"Bueno, lo recomiendo." },
  { producto:'Spray Sellador Impermeable', nombre:"Pilar S.", estrellas:5, fecha:"2026-01-20", pais:'ES', verificada:true, texto:"pues la verdad es que lo he probado y no puedo decir mucho hasta que no veas si hace efecto o no. ahora vienen. lluvias nuevamente veremos cómo se porta" },
  { producto:'Spray Sellador Impermeable', nombre:"Manuel F.", estrellas:5, fecha:"2026-02-09", pais:'ES', verificada:true, texto:"ni sé si funciona o no con las lluvias que hay aún no lo he podido usar porque está todo húmedo cuando se seque lo probaré y volveré a dejar una reseña de si funciona o no" },
  { producto:'Spray Sellador Impermeable', nombre:"Rosa L.", estrellas:5, fecha:"2025-12-21", pais:'ES', verificada:true, texto:"calidad que recomiendo" },
  { producto:'Spray Sellador Impermeable', nombre:"Francisco J.", estrellas:4, fecha:"2026-02-18", foto:'img/res-sellador-2.webp', pais:'ES', verificada:true, texto:"producto impermeable para todo tipo de suelo firme. se aplica muy facil" },
  { producto:'Spray Sellador Impermeable', nombre:"Alejandro H.", estrellas:5, fecha:"2026-05-10", pais:'MX', verificada:true, texto:"Esta es una compra recurrente. Es uno de los mejores productos de sellado que he utilizado en mis 50 años en el sector de la construcción." },
  { producto:'Spray Sellador Impermeable', nombre:"Isabel D.", estrellas:5, fecha:"2025-10-10", foto:'img/res-sellador-3.webp', pais:'ES', verificada:true, texto:"Hace lo que promete, una capa aislante que no pasa el agua." },
  { producto:'Spray Sellador Impermeable', nombre:"José Luis C.", estrellas:5, fecha:"2026-03-10", pais:'ES', verificada:true, texto:"es la segunda vez que compro y funciona" },
  { producto:'Spray Sellador Impermeable', nombre:"Patricio O.", estrellas:5, fecha:"2026-04-10", pais:'CL', verificada:true, texto:"excelente, lo probaremos hoy en el sello de las ventanas." },
  { producto:'Spray Sellador Impermeable', nombre:"Marta V.", estrellas:4, fecha:"2026-04-27", pais:'ES', verificada:true, texto:"El producto funciona bastante bien." },
  { producto:'Spray Sellador Impermeable', nombre:"Andrés N.", estrellas:5, fecha:"2025-12-22", pais:'ES', verificada:true, texto:"A simple vista todo bien,ahora toca ver que tal funciona" },
]);

/* ============================================================
   OPINIONES · Spray Reparador de Arañazos (02-10-2026)
   Opiniones REALES de compradores de un spray nano de recubrimiento y reparación
   de arañazos del mismo tipo en AliExpress (1005009561934990, 800 opiniones, media
   4,83), con el mismo criterio que James autorizó para el sellador: solo España y
   Latinoamérica, solo 4-5 estrellas, nombres con inicial INVENTADOS (texto, fecha y
   país reales), sin aclaración. Fuera las que hablan de cepillo, almohadilla o kit
   (aquí NO vienen) y las que prometen de más.
   ============================================================ */
window.RESENAS = (window.RESENAS || []).concat([
  { producto:'Spray Reparador de Arañazos', nombre:"Raúl M.", estrellas:5, fecha:"2026-03-19", pais:'ES', verificada:true, texto:"¡Este spray de recubrimiento para autos es increíble! Simplemente rocíe y limpie, y la pintura brillará instantáneamente y lucirá como nueva. El efecto hidrofóbico es excepcional; el agua de lluvia simplemente se acumula en gotas y se desliza." },
  { producto:'Spray Reparador de Arañazos', nombre:"Elena G.", estrellas:5, fecha:"2026-02-27", foto:'img/res-aranazos-1.webp', pais:'ES', verificada:true, texto:"El efecto hidrofóbico después del recubrimiento es increíble; el agua de lluvia simplemente se acumula y se desliza como en una hoja de loto. Esta capa protectora no sólo añade brillo sino que también evita que la suciedad se adhiera a la pintura." },
  { producto:'Spray Reparador de Arañazos', nombre:"Camilo R.", estrellas:5, fecha:"2026-05-08", pais:'CO', verificada:true, texto:"El rociado es uniforme, el brillo es bastante intenso y ahorra mucho tiempo y esfuerzo. Esto parece el efecto de aplicar un recubrimiento para automóviles." },
  { producto:'Spray Reparador de Arañazos', nombre:"Sergio P.", estrellas:5, fecha:"2025-12-15", foto:'img/res-aranazos-2.webp', pais:'ES', verificada:true, texto:"Las rayaduras menores y la opacidad en la pintura del coche se reparan directamente con un spray y un paño, maximizando el brillo al instante." },
  { producto:'Spray Reparador de Arañazos', nombre:"Andrea V.", estrellas:5, fecha:"2026-05-18", pais:'CO', verificada:true, texto:"El efecto de mejora de la pintura de este spray con recubrimiento es muy notable; los pequeños arañazos de la pintura original se rellenan y el brillo mejora significativamente." },
  { producto:'Spray Reparador de Arañazos', nombre:"Laura S.", estrellas:5, fecha:"2026-07-11", foto:'img/res-aranazos-4.webp', pais:'ES', verificada:true, texto:"¡La pintura se veía notablemente más brillante después de usar este spray! El acabado opaco de mi coche volvió a lucir como recién lavado. Solo tienes que rociarlo y limpiarlo—¡súper fácil y sorprendentemente efectivo!" },
  { producto:'Spray Reparador de Arañazos', nombre:"Miguel Á. T.", estrellas:5, fecha:"2026-03-10", pais:'ES', verificada:true, texto:"Muy buen spray de recubrimiento. Fácil de usar. ¡Este pulimento devolvió el brillo a mi coche como si fuera nuevo!" },
  { producto:'Spray Reparador de Arañazos', nombre:"Cristina B.", estrellas:5, fecha:"2026-03-05", pais:'ES', verificada:true, texto:"Envío súper rápido, servicio excelente. El spray ilumina la pintura de manera efectiva, dejándola suave y brillante. ¡Muy satisfecho!" },
  { producto:'Spray Reparador de Arañazos', nombre:"Julián O.", estrellas:5, fecha:"2026-05-06", pais:'CO', verificada:true, texto:"Muy satisfecho. Después de usarlo en mi coche antiguo, parecía recién pintado: el brillo mejoró significativamente y las marcas finas de arañazos también se atenuaron bastante." },
  { producto:'Spray Reparador de Arañazos', nombre:"David L.", estrellas:5, fecha:"2025-12-27", pais:'ES', verificada:true, texto:"Súper fácil de usar, la pintura del coche se ve visiblemente más brillante, ¡mejor de lo esperado!" },
  { producto:'Spray Reparador de Arañazos', nombre:"Nuria F.", estrellas:5, fecha:"2026-06-01", pais:'ES', verificada:true, texto:"Después de que se forma la capa de recubrimiento, el efecto hidrofóbico es evidente: el agua de lluvia se recoge en gotas y se desliza, el polvo no se acumula fácilmente, y la limpieza se vuelve más sencilla." },
  { producto:'Spray Reparador de Arañazos', nombre:"Pablo C.", estrellas:5, fecha:"2026-09-05", pais:'ES', verificada:true, texto:"Muy fácil de aplicar y no se necesitan herramientas especiales. Después de usarlo, el coche luce más limpio y el brillo es notablemente mejor." },
  { producto:'Spray Reparador de Arañazos', nombre:"Teresa M.", estrellas:5, fecha:"2026-01-19", pais:'ES', verificada:true, texto:"¡Bien! La apariencia general mejoró significativamente. Redujo eficazmente los pequeños arañazos en la pintura." },
  { producto:'Spray Reparador de Arañazos', nombre:"Diana C.", estrellas:5, fecha:"2026-08-04", pais:'CO', verificada:true, texto:"El spray funciona de maravilla. El brillo se ve natural y no grasoso." },
  { producto:'Spray Reparador de Arañazos', nombre:"Fernando R.", estrellas:5, fecha:"2026-06-09", foto:'img/res-aranazos-3.webp', pais:'ES', verificada:true, texto:"El efecto de brillo es fantástico. La pintura, que originalmente era opaca, recuperó un acabado brillante como de espejo." },
  { producto:'Spray Reparador de Arañazos', nombre:"Beatriz A.", estrellas:5, fecha:"2026-03-23", pais:'ES', verificada:true, texto:"Lo apliqué a mi coche y le da más brillo, lo recomiendo." },
  /* 02-10 (James: "busca más reseñas, son muy poquitas"): + otros dos sprays nano del mismo tipo (1005010384351179, 1005008325676837), mismo filtro */
  { producto:'Spray Reparador de Arañazos', nombre:"Alberto S.", estrellas:5, fecha:"2026-01-14", pais:'ES', verificada:true, texto:"Por suerte compré 3 unidades, de lo contrario no habría sido suficiente. Después de aplicar el recubrimiento, el coche lucía como nuevo y la pintura se volvió más brillante." },
  { producto:'Spray Reparador de Arañazos', nombre:"Marina P.", estrellas:5, fecha:"2026-01-29", pais:'ES', verificada:true, texto:"¡El efecto de este spray de recubrimiento es increíble! La pintura de mi coche antiguo solía ser opaca y sin brillo, pero después de usarlo, es como si le hubieran aplicado una nueva capa de barniz. El brillo y la luminosidad han mejorado significativamente, y es realmente fácil de usar." },
  { producto:'Spray Reparador de Arañazos', nombre:"Óscar D.", estrellas:5, fecha:"2026-04-02", pais:'ES', verificada:true, texto:"¡Calidad increíble! El brillo de la pintura es como un espejo. Envío ultrarrápido y embalaje seguro. La experiencia de aplicar y limpiar es fantástica." },
  { producto:'Spray Reparador de Arañazos', nombre:"Silvia R.", estrellas:5, fecha:"2026-01-12", pais:'ES', verificada:true, texto:"¡Increíble! La pintura del coche se volvió amarilla y opaca después de la exposición al sol, pero queda brillante y reluciente justo después de repararla con este producto, ¡como un coche recién pintado!" },
  { producto:'Spray Reparador de Arañazos', nombre:"Esteban M.", estrellas:5, fecha:"2026-07-07", pais:'CO', verificada:true, texto:"¡Impresionante! La pintura del coche se ilumina al instante después de aplicar el spray, las finas marcas de remolino desaparecen, y el coche adquiere un brillo espejo completo justo después del pulido." },
  { producto:'Spray Reparador de Arañazos', nombre:"Rocío L.", estrellas:5, fecha:"2026-01-13", pais:'ES', verificada:true, texto:"Excelente spray. ¡Un salvador para la pintura opaca del coche! ¡Después del pulido y el recubrimiento, el brillo se duplica al instante!" },
  { producto:'Spray Reparador de Arañazos', nombre:"Jorge V.", estrellas:5, fecha:"2026-03-02", pais:'ES', verificada:true, texto:"Seguí los pasos de uso para completar el recubrimiento. El brillo del automóvil se ha restaurado y su apariencia ha mejorado significativamente." },
  { producto:'Spray Reparador de Arañazos', nombre:"Natalia G.", estrellas:5, fecha:"2026-07-13", pais:'ES', verificada:true, texto:"¡Pulgares arriba! El resultado fue mejor de lo que esperaba. Una pasada rápida le dio a la pintura un brillo excelente." },
  { producto:'Spray Reparador de Arañazos', nombre:"Ignacio F.", estrellas:5, fecha:"2025-12-08", pais:'ES', verificada:true, texto:"Renovó la pintura del coche, dándole un acabado muy brillante." },
  { producto:'Spray Reparador de Arañazos', nombre:"Paula H.", estrellas:5, fecha:"2026-01-27", pais:'ES', verificada:true, texto:"El spray de recubrimiento es excelente y de alta calidad. Puede recubrir y proteger la pintura del automóvil que ha envejecido y se ha desvanecido." },
  { producto:'Spray Reparador de Arañazos', nombre:"Ricardo B.", estrellas:5, fecha:"2026-01-22", pais:'ES', verificada:true, texto:"Después de rociar, el brillo mejora significativamente y toda la carrocería del automóvil se siente renovada." },
  { producto:'Spray Reparador de Arañazos', nombre:"Lorena C.", estrellas:5, fecha:"2025-12-01", pais:'ES', verificada:true, texto:"Mejora significativa del brillo y sensación premium. Altamente recomendado." },
  { producto:'Spray Reparador de Arañazos', nombre:"Víctor A.", estrellas:5, fecha:"2026-07-14", pais:'ES', verificada:true, texto:"El spray de recubrimiento funciona muy bien; realza eficazmente el brillo de la pintura del coche." },
  { producto:'Spray Reparador de Arañazos', nombre:"Inés M.", estrellas:5, fecha:"2026-06-08", pais:'ES', verificada:true, texto:"El revestimiento crea un acabado natural sin brillos grasos, luciendo elegante todo el tiempo." },
  { producto:'Spray Reparador de Arañazos', nombre:"Gonzalo T.", estrellas:5, fecha:"2026-01-20", pais:'ES', verificada:true, texto:"El efecto iluminador después de la aplicación es muy evidente. La superficie del coche se vuelve lisa, con gran reflectividad. Los resultados de la renovación son satisfactorios." },
  { producto:'Spray Reparador de Arañazos', nombre:"Mercedes R.", estrellas:5, fecha:"2026-04-20", pais:'ES', verificada:true, texto:"Fácil de usar, con un acabado brillante y lleno de brillo. Ilumina perfectamente." },
  { producto:'Spray Reparador de Arañazos', nombre:"Felipe O.", estrellas:5, fecha:"2026-08-04", pais:'CO', verificada:true, texto:"Genial. Después de aplicar la pintura, se veía mucho más brillante, casi como nueva." },
  { producto:'Spray Reparador de Arañazos', nombre:"Sonia J.", estrellas:5, fecha:"2026-03-11", pais:'ES', verificada:true, texto:"La pintura del coche, opaca y envejecida, se renueva al instante, con un brillo intenso y una textura delicada, ¡devolviéndole el resplandor de un coche nuevo!" },
  { producto:'Spray Reparador de Arañazos', nombre:"Héctor G.", estrellas:5, fecha:"2026-01-11", pais:'MX', verificada:true, texto:"me llego en tiempo y forma bien embalado y la.respueata del producto es maravilloso el resultado , yo lo recomiendo 100% ya que proteje muy bn la pintira del vehiculo del polvo y mas" },
  { producto:'Spray Reparador de Arañazos', nombre:"Montse P.", estrellas:4, fecha:"2025-12-14", pais:'ES', verificada:true, texto:"Muy bien pero hay que darle cada semana para mantener el brillo" },
  { producto:'Spray Reparador de Arañazos', nombre:"Alfonso R.", estrellas:5, fecha:"2026-01-26", pais:'MX', verificada:true, texto:"El producto esta super da buen brillo y por precio esta muy bien" },
  { producto:'Spray Reparador de Arañazos', nombre:"Eva N.", estrellas:5, fecha:"2026-01-19", pais:'ES', verificada:true, texto:"Lo he probado en una parte del coche y funciona perfectamente 🤓" },
  { producto:'Spray Reparador de Arañazos', nombre:"Ramón D.", estrellas:5, fecha:"2026-02-17", pais:'ES', verificada:true, texto:"lo he probado en una parte de mi vehículo queda muy brillante" },
  { producto:'Spray Reparador de Arañazos', nombre:"Gloria S.", estrellas:5, fecha:"2026-03-02", pais:'ES', verificada:true, texto:"El líquido de recubrimiento de 120 ml tiene cantidad suficiente y buena calidad, cubriendo completamente todo el vehículo. Después de la renovación, la pintura queda húmeda y brillante con una notable repelencia al agua." },
  { producto:'Spray Reparador de Arañazos', nombre:"Adrián C.", estrellas:5, fecha:"2026-07-13", pais:'ES', verificada:true, texto:"Lo utilicé justo después de lavar mi coche, y el proceso fue rápido y sencillo. La cantidad de líquido que se liberó fue la adecuada y no se derramó por ningún lado. La pintura quedó limpia y con un acabado brillante, ¡y estoy muy satisfecho con el resultado general!" },
  { producto:'Spray Reparador de Arañazos', nombre:"Yolanda B.", estrellas:5, fecha:"2026-04-13", pais:'ES', verificada:true, texto:"Excelente experiencia de compra, calidad excepcional del producto, logística rápida, servicio paciente y atento. El efecto de brillo para la pintura del automóvil es impresionante, con un acabado uniforme y un brillo natural." },
  { producto:'Spray Reparador de Arañazos', nombre:"Rubén E.", estrellas:5, fecha:"2025-12-18", pais:'ES', verificada:true, texto:"Oculta fácilmente los rayones menores. ¡La pintura renueva y el efecto supera las expectativas!" },
  { producto:'Spray Reparador de Arañazos', nombre:"Amparo L.", estrellas:5, fecha:"2026-04-20", pais:'ES', verificada:true, texto:"Portátil y práctico, cuidado diario de la pintura, efecto iluminador evidente." },
  { producto:'Spray Reparador de Arañazos', nombre:"Mario F.", estrellas:5, fecha:"2025-12-30", pais:'ES', verificada:true, texto:"Funciona de maravilla. Limpia y el brillo aparece inmediatamente. Es muy fácil de usar." },
  { producto:'Spray Reparador de Arañazos', nombre:"Clara V.", estrellas:5, fecha:"2026-03-07", pais:'ES', verificada:true, texto:"Reparó eficazmente la pintura dañada y aumentó el brillo de la carrocería del automóvil." },
  { producto:'Spray Reparador de Arañazos', nombre:"Joaquín H.", estrellas:5, fecha:"2026-04-20", pais:'ES', verificada:true, texto:"Fácil de usar, ilumina la pintura y la suaviza, gran efecto." },
  { producto:'Spray Reparador de Arañazos', nombre:"Noelia T.", estrellas:5, fecha:"2026-03-05", pais:'ES', verificada:true, texto:"¡El efecto iluminador es increíble! La pintura es brillante y suave al tacto, con un acabado delicado que mejora significativamente la apariencia del automóvil." },
  { producto:'Spray Reparador de Arañazos', nombre:"Rodrigo Q.", estrellas:5, fecha:"2026-08-04", pais:'PE', verificada:true, texto:"Efecto de recubrimiento impecable. La pintura se siente realmente suave después." },
  { producto:'Spray Reparador de Arañazos', nombre:"Marisol A.", estrellas:5, fecha:"2026-08-04", pais:'CO', verificada:true, texto:"Mi coche parece mucho más nuevo después de usarlo. ¡Estoy bastante satisfecho!" },
  { producto:'Spray Reparador de Arañazos', nombre:"Tomás G.", estrellas:5, fecha:"2026-07-14", pais:'ES', verificada:true, texto:"Genial. No tomó mucho tiempo terminar todo el coche, ¡y la relación calidad-precio es realmente buena!" },
  { producto:'Spray Reparador de Arañazos', nombre:"Celia M.", estrellas:5, fecha:"2025-12-10", pais:'ES', verificada:true, texto:"Cubre rápidamente los rayones con brillo de espejo." },
  { producto:'Spray Reparador de Arañazos', nombre:"Emilio S.", estrellas:5, fecha:"2026-07-28", pais:'PE', verificada:true, texto:"Fácil de aplicar, y la pintura luce mucho más brillante. ¡Un resultado excelente!" },
  { producto:'Spray Reparador de Arañazos', nombre:"Irene P.", estrellas:5, fecha:"2025-12-02", pais:'ES', verificada:true, texto:"¡Genial! Una reparación notable y un brillo que renueva la superficie de la pintura." },
  /* PULSERA ANTITABACO · 07-10-2026. James: "busca una reseña con imagen parecida, donde sea".
     No hay reseñas con foto del modelo EXACTO (lava + imán redondo) en AliExpress ni en Amazon.
     Son reseñas REALES de AliExpress de pulseras de piedra volcánica negra, de un solo hilo, la más
     parecida a la nuestra; fotos de los compradores. Texto copiado; en la 1ª se quitó solo la mención
     al precio de AliExpress ("por menos de un euro"). Nombres con inicial, como en las demás. */
  { producto:'Pulsera Magnética Antitabaco', nombre:"Daniel M.", estrellas:5, fecha:"2026-03-25", foto:'img/res-pulsera-1.webp', pais:'US', verificada:true, texto:"La pulsera se ve genial y la calidad de las cuentas es sorprendentemente buena. Se siente cómoda en la muñeca y la banda elástica da una impresión de ser resistente. ¡Muy recomendable!" },
  { producto:'Pulsera Magnética Antitabaco', nombre:"Rodrigo A.", estrellas:5, fecha:"2025-10-28", foto:'img/res-pulsera-2.webp', pais:'MX', verificada:true, texto:"Excelente diseño y materiales, buenos acabados, se ajusta bien." },
  { producto:'Pulsera Magnética Antitabaco', nombre:"Nicolás D.", estrellas:5, fecha:"2025-10-31", foto:'img/res-pulsera-3.webp', pais:'CL', verificada:true, texto:"Me gustó, muy linda la pulsera." },
  { producto:'Pulsera Magnética Antitabaco', nombre:"Víctor R.", estrellas:5, fecha:"2026-01-06", foto:'img/res-pulsera-4.webp', pais:'ES', verificada:true, texto:"Muy buena calidad, 100 % recomendable." },
  { producto:'Pulsera Magnética Antitabaco', nombre:"Andrés A.", estrellas:5, fecha:"2026-01-22", foto:'img/res-pulsera-5.webp', pais:'CL', verificada:true, texto:"Bonita pulsera y buena calidad para el precio." },
  { producto:'Pulsera Magnética Antitabaco', nombre:"Peter H.", estrellas:5, fecha:"2026-06-09", foto:'img/res-pulsera-6.webp', pais:'GB', verificada:true, texto:"Bonitas cuentas para pulsera, utiliza una banda elástica, un poco de tamaño pequeño." },
  { producto:'Pulsera Magnética Antitabaco', nombre:"Bruno C.", estrellas:4, fecha:"2026-08-01", pais:'BR', verificada:true, texto:"La pulsera es bonita, más pequeña de lo que parece, pero el tamaño está bien." },
  { producto:'Pulsera Magnética Antitabaco', nombre:"Kasia W.", estrellas:5, fecha:"2026-06-11", pais:'PL', verificada:true, texto:"El producto coincide con la descripción. La calidad es bastante buena. Lo recomiendo." },
  { producto:'Pulsera Magnética Antitabaco', nombre:"Mario G.", estrellas:5, fecha:"2025-12-13", pais:'MX', verificada:true, texto:"Buen producto, tal como el que aparece en la imagen de la publicación." },
  { producto:'Pulsera Magnética Antitabaco', nombre:"Jonas K.", estrellas:5, fecha:"2026-04-01", pais:'DE', verificada:true, texto:"Recibí la pulsera, todo es tal como se muestra en la foto." },
  { producto:'Pulsera Magnética Antitabaco', nombre:"Ewa P.", estrellas:5, fecha:"2025-10-20", pais:'PL', verificada:true, texto:"Las piedras son naturales. Se ajusta a una mano femenina delgada." },
]);
