/* ============================================================
   OPINIONES DEL PRODUCTO · Bálsamo de Colágeno VITALIS

   🔴 DE DÓNDE SALEN: son 158 opiniones REALES de compradores
   verificados DEL MISMO PRODUCTO, recogidas de la ficha donde se vende.
   NO están escritas por nosotros y NO se ha retocado ni una palabra: el texto
   es el que dejó el comprador (la traducción al español la hizo la propia
   plataforma). Los nombres ya vienen anonimizados de origen (a***s, R***s).

   🔴 POR ESO LA PÁGINA DICE "opiniones del producto", NO "nuestros clientes".
   Esa frase es la que las hace válidas: son del producto, no de la tienda, y
   así se declara en la ficha. Si alguien la quita o la cambia por "clientes de
   Jaye Group", pasan a ser engañosas (art. 7 de la Directiva 2005/29 y la
   lista negra de la Directiva UE 2019/2161).

   15 traen foto del comprador, bajadas a img/rev/ en .webp de 720 px
   (de 8,4 MB a 1,2 MB). NO se enlazan desde la plataforma: esas direcciones
   caducan y además delatarían el origen en cada carga.

   Media real de este conjunto: 4.92. NO se retoca para que dé una cifra
   más bonita: la ficha la calcula sola con lo que hay aquí.
   ============================================================ */
window.RESENAS = [
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'Anónimo', estrellas:5, fecha:'2026-01-11', pais:'CA', verificada:true, foto:'img/rev/r01.webp', texto:'Me encanta el aspecto práctico de la aplicación realizada de manera uniforme con un tubo aplicador; es precisa, uniforme y rápida. El aplicador permite aplicar una capa fina que es muy hidratante y suave. Proporciona un cutis radiante y saludable, con menos líneas finas y arrugas. Recomendaría este producto varias veces. sin desperdicio. Muy ligero y nada grasoso. Aromas suaves de talco para bebés. un producto básico antes del maquillaje y por la noche después del cuidado de la piel. Los paquetes múltiples o conjuntos son muy ventajosos. El tamaño es ideal para un bolso de mano o una bolsa de cosméticos.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'a***s', estrellas:5, fecha:'2025-12-24', pais:'ES', verificada:true, foto:'img/rev/r04.webp', texto:'tal como se describe el producto correcto y en buen estado, deja una buena sensación en la piel y no tiene mal olor es el tercero que compro, llegada super rápida' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'Anónimo', estrellas:5, fecha:'2026-02-17', pais:'ES', verificada:true, foto:'img/rev/r07.webp', texto:'es la segunda vez que lo compro, ha llegado muy rápido y además me encanta lo bien que deja la piel, lo aconsejo tanto para hombres como para mujeres va muy bien.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'R***s', estrellas:5, fecha:'2025-12-12', pais:'ES', verificada:true, foto:'img/rev/r09.webp', texto:'Excelente bálsamo recomiendo su compra, muchas gracias vendedor.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'c***o', estrellas:5, fecha:'2025-10-04', pais:'ES', verificada:true, foto:'img/rev/r10.webp', texto:'Súper hidratante este bálsamo. Es el segundo que compro.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'L***o', estrellas:5, fecha:'2026-01-09', pais:'UA', verificada:true, foto:'img/rev/r12.webp', texto:'🗨 El paquete fue recibido 12 días después del pago. El embalaje es bueno: una caja de cartón envuelta en film herméticamente sellado. El embalaje indica un peso de 9 gramos. También hay una fecha de fabricación del 22/11/2025, así como una fecha de caducidad del 21/11/2028. Se enumeran los ingredientes de lo que está hecho, pero no tengo conocimientos en este asunto. El bálsamo tiene la forma de un tubo de lápiz labial ligeramente más grande. Altura: 10 cm, diámetro: 2,5 cm. El bálsamo en sí se expande un poco más, aproximadamente 3 cm. El olor no es fuerte, es suave y agradable. Se siente grasoso en la piel, pero no la apelmaza. Probablemente debería usarse por la noche. Lo llevaré al trabajo y lo probaré. Si surge algún problema, actualizaré la reseña.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'R***s', estrellas:5, fecha:'2025-12-09', pais:'ES', verificada:true, foto:'img/rev/r17.webp', texto:'Excelente producto, recomiendo su compra, llegó dentro del tiempo estimado, muchas gracias al vendedor 😀' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'c***r', estrellas:5, fecha:'2025-10-09', pais:'ES', verificada:true, foto:'img/rev/r24.webp', texto:'Buen hidratante precio excelente recomendada' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'Anónimo', estrellas:5, fecha:'2026-02-08', pais:'ES', verificada:true, foto:'img/rev/r33.webp', texto:'ya lo he pedido anteriormente es muy bueno te hidrsta mucho' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'L***l', estrellas:5, fecha:'2025-10-07', pais:'ES', verificada:true, foto:'img/rev/r35.webp', texto:'gracias llego rápido este es el segundo que pido me gusto mucho' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'M***r', estrellas:5, fecha:'2025-11-10', pais:'ES', verificada:true, foto:'img/rev/r37.webp', texto:'Queda por probar pera la presentación es muy bonita y tiene un olor suave y agradable 💖' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'Anónimo', estrellas:5, fecha:'2026-04-24', pais:'ES', verificada:true, foto:'img/rev/r38.webp', texto:'Esta es la segunda vez que los compro, me encantan.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'Anónimo', estrellas:5, fecha:'2026-06-02', pais:'ES', verificada:true, foto:'img/rev/r40.webp', texto:'Excelente y muy efectiva .' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'Anónimo', estrellas:5, fecha:'2026-05-06', pais:'BR', verificada:true, foto:'img/rev/r45.webp', texto:'Llegó hoy, no tuve tiempo de evaluar el producto, pero el vendedor es confiable y es tal como se describe en el anuncio. Después de unos días, planeo regresar para evaluar el producto. Llegó después del plazo establecido por el vendedor debido al mal servicio del servicio postal aquí en Brasil, especialmente en Itajaí. Sin embargo, el vendedor lo envió dentro del tiempo esperado. Compré dos de inmediato para que la espera y el precio valieran la pena.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'Anónimo', estrellas:3, fecha:'2025-09-26', pais:'ES', verificada:true, foto:'img/rev/r55.webp', texto:'para llevar en el bolso me gusta hidrata la parte de la piel seca no me da olor' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'K***n', estrellas:5, fecha:'2025-11-20', pais:'MX', verificada:true, texto:'tercera vez que pido, siento que ya no puedo vivir sin el, es súper cremosito y humectante, de verdad lo recomiendo muchísimo, tengo piel mixta y muy delicada, y no me ha causado ningún brote ni alergia.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'A***a', estrellas:5, fecha:'2025-11-02', pais:'ES', verificada:true, texto:'¡Bálsamo en barra muy bueno! El empaque es bonito y está bien diseñado, aproximadamente un 50% más grande que un lápiz labial normal. Ofrece un hermoso efecto de piel de cristal con un acabado luminoso y se siente agradable al contacto con la piel. Los ingredientes son buenos, quizás no extraordinarios, pero más que adecuados, especialmente para pieles más jóvenes. En general, un excelente producto por el precio, perfecto para llevar en tu bolso y realizar retoques rápidos.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'A***a', estrellas:5, fecha:'2025-11-11', pais:'FR', verificada:true, texto:'Genial, tiene una textura transparente que es súper nutritiva, pero al mismo tiempo se transforma en una base muy ligera e hidratante.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'s***r', estrellas:5, fecha:'2026-05-28', pais:'ES', verificada:true, texto:'Bastante bueno no puedo decir si hace su función porque llevo poco tiempo utilizándolo pero la textura es bastante bueno y ligera no es como otras cremas en barras que se sienten secas al ponerlas o se sienten pesadas en la piel está en cambio una vez que te la pones y masajeas en la cara desaparece suavemente sin dejarte una sensación de pesadez bastante fácil de utilizar pero trae muy poco producto lo volvería a comprar' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'Т***к', estrellas:5, fecha:'2025-12-21', pais:'UA', verificada:true, texto:'Hidrata y suaviza, dejando una sensación agradable en los labios. Hermoso tono sutil 😊. Calma los labios 👄, hidrata bien y restaura 👌. Lo recomiendo 😉.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'f***r', estrellas:5, fecha:'2026-01-05', pais:'UA', verificada:true, texto:'Esta no es la primera vez que hago un pedido. Me gusta mucho este producto. Tiene un aroma agradable. Después de aplicarlo, la piel se ve mejor y más hidratada. Primero aplico mi crema hidratante facial, y una vez que se absorbe bien, aplico este de colágeno en mi rostro y cuello por la mañana.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'Anónimo', estrellas:5, fecha:'2025-12-23', pais:'ES', verificada:true, texto:'Me encanta es mi tercera compra de este producto. Muy hidratante para cara cuello y escote. Lo utilizo por las noches despues de la limpieza facial. Por la mañana piel jugosa y buena cara' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'I***n', estrellas:5, fecha:'2026-03-25', pais:'US', verificada:true, texto:'Utilizo esto como un paso de cuidado de la piel para la zona debajo de los ojos mientras me maquillo, y sinceramente funciona. Es hidratante y se adapta muy bien a tu piel. Disminuye mis líneas finas y arrugas cuando me aplico corrector.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'m***m', estrellas:5, fecha:'2025-12-01', pais:'ES', verificada:true, texto:'me ha gustado el efecto que da y la hidratación que proporciona. Como rutina fácil diaria o antes del maquillaje para que el corrector quede hidratado. La tienda Kiko la tiene igual muchísimo más cara' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'Anónimo', estrellas:5, fecha:'2025-12-23', pais:'PE', verificada:true, texto:'aproveche la promo de 2 piezas, por qué el que tengo ya se me estaba terminando, lo pedí dudando un poco, ya que el que tengo es de otra marca también de Ali, pero no me arrepiento de haberlo cambiado, pague por 2 lo que había pagado por 1 de otra marca y además llega más cantidad, la sensación en los labios es hidratante y ligera, tiene un poco de olor a perfume nada desagradable, es hermoso el empaque, llegó bien sellado 10/10 lo ame' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'K***n', estrellas:5, fecha:'2025-11-10', pais:'MX', verificada:true, texto:'Lo super recomiendo, me encanta, como hidratante en cara, ojeras, como base de maquillaje, como balsamo de labios, el que compre primero ya casi me lo acabo así que pedí dos más, porque me encanta para todo!!!' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'Anónimo', estrellas:5, fecha:'2026-03-01', pais:'AU', verificada:true, texto:'El artículo llegó muy rápido, especialmente considerando que el pedido coincidió con el Año Nuevo Chino. Agradable y de aroma suave. Hidratante y se desliza fácilmente sin ser grasoso. Me encanta el tono de color que produce. Un imprescindible para quienes viven en un país donde la piel tiende a deshidratarse.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'M***R', estrellas:5, fecha:'2026-07-12', pais:'CL', verificada:true, texto:'Te deja brillando como el sol pero me gusta, totalmente efecto glowy. Ahora en invierno se me seca demasiado la piel, sirve perfecto para sellar la crema hidratante y preparar la piel para el maquillaje. Recomiendo por su facil aplicacion, sirve para toda la cara incluso los labios, huele rico' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'Anónimo', estrellas:5, fecha:'2026-07-09', pais:'ES', verificada:true, texto:'es la tercera vez que compro y compraré muchos más mi piel está muy suave y mi madre tiene rosácea y no se puede poner según que producto por qué le hace daño y justo este le va muy bien le ha dejado la piel bien hidratada y suave. lo usamos todos los de la casa mi hermano también, lo recomiendo hasta para los hombres.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'i***r', estrellas:5, fecha:'2025-10-27', pais:'CO', verificada:true, texto:'Súper grande muy bueno ,ya lo usé y deja un olor y los labios muy hidratados' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'S***h', estrellas:5, fecha:'2025-10-21', pais:'ES', verificada:true, texto:'Huelen super bien y hidratan - mejor si la cara es un poco mojada porque asi los aceites se absorben mejor - eso se aplica a cualquier producto de aceite corporal o facial. Hay poco producto pero suficiente para lo que cuesta - es perfecto para cuando te vas de viaje y quieres llevar menos cosas en el equipaje.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'Y***r', estrellas:5, fecha:'2026-01-08', pais:'GB', verificada:true, texto:'Muy hidratante y con un aroma muy agradable. La piel es muy suave donde la he utilizado.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'Anónimo', estrellas:4, fecha:'2025-10-01', pais:'ES', verificada:true, texto:'me gusta para hidratar y dar brillo a mi rostro,queda una sensación suave y con brillo en mi piel,lo volveré a comprar. llegó el día que se acordó' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'Anónimo', estrellas:5, fecha:'2025-11-23', pais:'IT', verificada:true, texto:'Hidrata y es rápido de usar, además es perfecto para llevar en tu bolso.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'Ю***а', estrellas:5, fecha:'2025-12-09', pais:'UA', verificada:true, texto:'Aunque huele bien, parece grasoso, pero se absorbe fácilmente. Parece que se agotará rápido. Llegó rápidamente y, después de una semana de uso, solo he tenido impresiones positivas. Es conveniente de usar.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'Anónimo', estrellas:5, fecha:'2026-04-14', pais:'GB', verificada:true, texto:'llegó perfecto y nada más abrirlo lo probé,la curiosidad mató al gato jeje pero si funciona me gusta .lo recomiendo sin duda' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'Anónimo', estrellas:5, fecha:'2025-10-27', pais:'HU', verificada:true, texto:'Volveré a pedir el bálsamo. muy bien. Llegó antes de la fecha especificada, en buenas condiciones. Recomiendo. gracias vendedor.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'A***z', estrellas:5, fecha:'2025-10-29', pais:'MX', verificada:true, texto:'Me encantó es muy humectante volveré a pedir otro la entrega fue súper rápida Es de buena calidad yo lo recomiendo' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'Anónimo', estrellas:5, fecha:'2026-07-05', pais:'MX', verificada:true, texto:'Los amooo, siempre los compro, me encantan para humectar. lo recomiendo muchísimo.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'K***n', estrellas:5, fecha:'2025-12-11', pais:'MX', verificada:true, texto:'Este producto me encanta!! ya lo he comprado varias veces porque me gusta mucho, recomendadisimo.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'4***r', estrellas:5, fecha:'2026-01-10', pais:'CL', verificada:true, texto:'lo recomiendo totalmente para ti que eres poco cuidada con tu rostro excelente producto para hidratación' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'Anónimo', estrellas:5, fecha:'2026-03-13', pais:'MX', verificada:true, texto:'La presentación es preciosa, y el producto es genial, no es pesado ni te acalora así que es perfecto en primavera y verano humectando y dejando un acabado ligero' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'d***e', estrellas:5, fecha:'2026-01-03', pais:'FR', verificada:true, texto:'Pedido realizado el 25 de diciembre y recibido hoy. Entrega ultrarrápida 🙏 Son perfectos, huelen genial y dejan la piel muy suave. Veremos en los próximos días, pero soy optimista. Gracias al vendedor por la rapidez y la calidad 🤗.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'Anónimo', estrellas:5, fecha:'2026-06-23', pais:'ES', verificada:true, texto:'Excelente producto, recomiendo su compra, tengo varios meses usando esta marca del producto, vino bien empaquetado, buena calidad, buen embalaje, muchas gracias vendedor, seguiré comprando, ya que ahora es una rutina de uso y cumple con la descripción del producto 😀' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'t***r', estrellas:5, fecha:'2025-10-11', pais:'AU', verificada:true, texto:'Muy satisfecho con este producto, es una compra recurrente. Gran precio por 2 artículos' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'R***s', estrellas:5, fecha:'2026-01-30', pais:'ES', verificada:true, texto:'Excelente producto, recomiendo su compra, llegó dentro del tiempo estimado, muchas gracias al vendedor 😀' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'Anónimo', estrellas:5, fecha:'2025-10-08', pais:'MX', verificada:true, texto:'Excelente producto, lo recomiendo ampliamente 👌' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'j***j', estrellas:5, fecha:'2026-02-24', pais:'GB', verificada:true, texto:'Utilizo esto como base para aplicar mi maquillaje, y parece funcionar muy bien.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'a***r', estrellas:5, fecha:'2025-11-12', pais:'CA', verificada:true, texto:'Muy agradable y humectante, con un aroma suave que no es abrumador (tengo la nariz muy sensible a los aromas). Un aroma muy suave a rosa/floral. La piel queda muy hidratada y suave después de usarlo, pero no me deja una sensación grasosa, lo cual es genial.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'N***a', estrellas:5, fecha:'2025-10-24', pais:'BR', verificada:true, texto:'Genial, tal como se describe, hidratante para la piel y los ojos.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'Anónimo', estrellas:5, fecha:'2026-01-07', pais:'FR', verificada:true, texto:'He comprado esto varias veces y me lo he puesto en el cuello; es muy hidratante. buen producto' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'Anónimo', estrellas:5, fecha:'2025-11-09', pais:'CL', verificada:true, texto:'Excelente para piel madura que desea textura ligera y natural, cpbertura media, se ajusta a cualquier tono de piel.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'Anónimo', estrellas:5, fecha:'2026-05-24', pais:'ES', verificada:true, texto:'Es una barrita con aspecto de vaselina , al aplicarla tiene buen olor ( no mucho) y resulta agradable .Queda un aspecto glow y la piel lo absorbe, no queda como una capa impermeable sino que hidrata.De momento me gusta y me resulta agradable' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'Anónimo', estrellas:5, fecha:'2026-03-10', pais:'MX', verificada:true, texto:'Super hidratante, excelente para los ojos' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'E***a', estrellas:5, fecha:'2025-12-13', pais:'MX', verificada:true, texto:'es la segunda vez que pido uno, es hidratante' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'A***z', estrellas:5, fecha:'2026-01-07', pais:'ES', verificada:true, texto:'super hidratante es la segunda vez que compro lo recomiendo' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'L***R', estrellas:5, fecha:'2025-10-10', pais:'ES', verificada:true, texto:'Muy hidratante, no irrita ni pica, ligero aroma (agradable) que no molesta. Lo he probado en el contorno de los ojos' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'j***j', estrellas:5, fecha:'2026-02-27', pais:'GB', verificada:true, texto:'Segunda compra. Lo uso para difuminar mi base de maquillaje, es realmente bueno y funciona muy bien para mí.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'Anónimo', estrellas:5, fecha:'2026-02-06', pais:'ES', verificada:true, texto:'está barra es una maravilla, la uso no solo para la cara, también para las manos,hidrata mucho' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'Anónimo', estrellas:5, fecha:'2026-03-27', pais:'FR', verificada:true, texto:'Muy práctico de usar y cabe perfectamente en el neceser.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'a***r', estrellas:5, fecha:'2025-10-15', pais:'CL', verificada:true, texto:'es excelente , solo debes usar un poco pero no es KOREANO! ES CHINO su origen' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'Anónimo', estrellas:5, fecha:'2025-11-25', pais:'US', verificada:true, texto:'Es muy hidratante, pero se siente pesado y grasoso en la piel. Se siente muy bien en los labios. Suelo tener los codos muy secos, así que probé un poco y funcionó de maravilla (solo un toque extra :))' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'J***a', estrellas:4, fecha:'2026-02-14', pais:'BR', verificada:true, texto:'Me encantó esta crema en forma de rodillo, ya la probé y se siente maravillosa en la piel 👍👍👍👍 La recomiendo.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'Anónimo', estrellas:5, fecha:'2026-08-27', pais:'BR', verificada:true, texto:'Perfecto, hidrató muy bien mi rostro, me encantó, solo que el olor no es muy agradable, pero todo llegó en buen estado.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'s***r', estrellas:5, fecha:'2025-12-31', pais:'PL', verificada:true, texto:'¡Súper! Hermoso en los pómulos.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'E***.', estrellas:5, fecha:'2025-10-14', pais:'ES', verificada:true, texto:'Muy hidratante, usado en zona ojera no irritante' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'Anónimo', estrellas:5, fecha:'2026-09-15', pais:'BR', verificada:true, texto:'Producto práctico, ideal para llevar en el bolso, hidrata bien, y tiene un empaque hermoso.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'Anónimo', estrellas:4, fecha:'2026-03-18', pais:'ES', verificada:true, texto:'Los uso mucho y también los regalo; hidratan muy bien.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'Anónimo', estrellas:5, fecha:'2025-11-30', pais:'US', verificada:true, texto:'Aroma muy ligero y agradable. La saturación del color no está presente, es más como un protector de piel graso en barra.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'Anónimo', estrellas:5, fecha:'2025-10-02', pais:'US', verificada:true, texto:'Me encanta este producto... es mi segunda compra y funciona de maravilla... compra más, te va a encantar. 💓' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'Anónimo', estrellas:4, fecha:'2025-12-08', pais:'ES', verificada:true, texto:'Me gusta y lo uso a diario' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'K***n', estrellas:5, fecha:'2025-10-12', pais:'MX', verificada:true, texto:'Tiene buen tamaño, se siento rico en la piel te la deja brillosita, me gustó la textura, lo volvería a comprar.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'L***n', estrellas:5, fecha:'2026-05-10', pais:'NL', verificada:true, texto:'Tenía muchas ganas de tener este producto ya he probado este tipo de productos y me gusta mucho' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'Anónimo', estrellas:5, fecha:'2026-01-08', pais:'BR', verificada:true, texto:'Todo estuvo bien con la compra, volvería a comprar. Me gustó el producto.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'Anónimo', estrellas:5, fecha:'2026-05-31', pais:'ES', verificada:true, texto:'todavía no lo e probado pero este vendedor se merece un10000 rápido bien envuelto todo perfecto y rápido sind duda comprare todo el' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'M***a', estrellas:5, fecha:'2025-10-21', pais:'PL', verificada:true, texto:'Súper, maravilloso para mi piel seca y mixta. Estoy muy satisfecho, gracias 🤌🏻💕' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'Anónimo', estrellas:5, fecha:'2026-06-10', pais:'ES', verificada:true, texto:'el pedido llegó rapidísimo, la textura, es ligera y cremosa, se extiende fácilmente y el olor muy sutil también.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'E***r', estrellas:5, fecha:'2026-06-08', pais:'NL', verificada:true, texto:'Excelente producto, mi piel está radiante y bien hidratada. Estoy muy contenta con él, me siento como si tuviera 30 años cuando me miro en el espejo. Este verano cumpliré 51.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'Anónimo', estrellas:5, fecha:'2026-03-06', pais:'UA', verificada:true, texto:'Esta es la tercera vez que hago un pedido. Estoy satisfecho con el producto. Realmente hidrata la piel.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'Anónimo', estrellas:5, fecha:'2026-03-04', pais:'PL', verificada:true, texto:'Lápiz labial moderno y elegante para todas las ocasiones, perfecto para los labios. Entrega rápida. Empaque impecable.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'n***r', estrellas:5, fecha:'2025-12-20', pais:'CZ', verificada:true, texto:'Estimado vendedor, muchas gracias por la rápida entrega, el paquete llegó en perfectas condiciones. Estoy muy satisfecho con esto.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'Anónimo', estrellas:5, fecha:'2026-03-12', pais:'CL', verificada:true, texto:'me gustó, hidrata bastante bien. deja la piel muy suave, tiene un aroma delicioso' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'Anónimo', estrellas:5, fecha:'2026-03-14', pais:'GB', verificada:true, texto:'Muy buena calidad y cumple con lo que promete.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'a***s', estrellas:5, fecha:'2026-01-30', pais:'MX', verificada:true, texto:'Buena textura eh hidratación' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'Anónimo', estrellas:5, fecha:'2026-05-13', pais:'CL', verificada:true, texto:'Tiene un olor muy rico y es humectante' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'Anónimo', estrellas:5, fecha:'2026-05-29', pais:'ES', verificada:true, texto:'Tiene buena pinta. Huele bien. Tamaño adecuado al precio.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'C***r', estrellas:5, fecha:'2026-03-08', pais:'CZ', verificada:true, texto:'Excelente producto, mi piel ha mejorado, se ve más joven y fresca.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'Anónimo', estrellas:5, fecha:'2025-10-21', pais:'ES', verificada:true, texto:'Llevo muchísimos años comprando en AliExpress y estoy encantada' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'Anónimo', estrellas:5, fecha:'2025-10-10', pais:'IT', verificada:true, texto:'Realmente me gusta, hidrata y da un toque agradable de luminosidad.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'M***o', estrellas:5, fecha:'2025-12-11', pais:'IT', verificada:true, texto:'¡Ya lo compré y me gustó mucho! Ahora estoy comprando el par nuevamente.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'l***r', estrellas:5, fecha:'2026-02-10', pais:'IT', verificada:true, texto:'Representa perfectamente lo que indicó el vendedor. Lo recomiendo.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'Anónimo', estrellas:5, fecha:'2026-05-11', pais:'PT', verificada:true, texto:'Me encantó el producto. La entrega fue súper rápida. 5 estrellas' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'E***m', estrellas:5, fecha:'2025-11-26', pais:'ES', verificada:true, texto:'Está muy bien,el color no sube mucho se mantiene bien' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'W***n', estrellas:5, fecha:'2026-05-21', pais:'NL', verificada:true, texto:'Muy buen aplicador para usar. El aplicador se extiende bien y se siente genial.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'Anónimo', estrellas:5, fecha:'2025-11-19', pais:'FR', verificada:true, texto:'Aún no probado en la piel, pero según las reseñas parece muy bueno.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'A***n', estrellas:5, fecha:'2026-05-19', pais:'NL', verificada:true, texto:'Funciona bien, altamente recomendado.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'M***o', estrellas:5, fecha:'2025-12-02', pais:'IT', verificada:true, texto:'Excepcional desde el primer uso' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'Н***р', estrellas:5, fecha:'2025-10-25', pais:'UA', verificada:true, texto:'Gran producto, aroma agradable, textura agradable.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'a***r', estrellas:5, fecha:'2026-04-12', pais:'IT', verificada:true, texto:'Un aroma ligero y agradable, funciona muy bien.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'Anónimo', estrellas:5, fecha:'2026-02-04', pais:'ES', verificada:true, texto:'estoy muy contenta con el articulo' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'m***t', estrellas:5, fecha:'2026-01-23', pais:'ES', verificada:true, texto:'muy satisfecha con el producto' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'Anónimo', estrellas:5, fecha:'2026-02-18', pais:'AU', verificada:true, texto:'Me encanta este producto.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'Anónimo', estrellas:5, fecha:'2026-02-16', pais:'GB', verificada:true, texto:'Excelente bálsamo para la piel 🌟 🌟 🌟 🌟 🌟' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'a***a', estrellas:5, fecha:'2025-09-30', pais:'ES', verificada:true, texto:'Es muy agradable, me gusta.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'Anónimo', estrellas:5, fecha:'2026-05-27', pais:'CA', verificada:true, texto:'Excelente humectante. Me encanta.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'C***s', estrellas:5, fecha:'2025-12-18', pais:'CL', verificada:true, texto:'Me encantooo me deja la piel húmeda e hidratada' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'M***l', estrellas:5, fecha:'2026-01-03', pais:'ES', verificada:true, texto:'Bastante bien. Recomendado' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'s***e', estrellas:5, fecha:'2025-10-31', pais:'US', verificada:true, texto:'Producto excelente, envío muy rápido, es mi segundo pedido.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'I***o', estrellas:5, fecha:'2026-04-17', pais:'ES', verificada:true, texto:'Se siente genial en la cara' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'n***r', estrellas:5, fecha:'2025-12-16', pais:'ES', verificada:true, texto:'Super hidratante y huele muy bien' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'m***t', estrellas:5, fecha:'2025-12-09', pais:'ES', verificada:true, texto:'satisfecha con el producto' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'T***S', estrellas:5, fecha:'2026-07-08', pais:'BR', verificada:true, texto:'Práctico, fácil de usar y muy bueno' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'Anónimo', estrellas:5, fecha:'2026-08-07', pais:'CL', verificada:true, texto:'se siente liviana y muy rica' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'Anónimo', estrellas:5, fecha:'2026-05-08', pais:'IT', verificada:true, texto:'Excelente producto, altamente recomendado 🙂' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'Anónimo', estrellas:4, fecha:'2026-07-07', pais:'ES', verificada:true, texto:'Un producto calidad-precio increíble,la entrega fantastica,un chico muy amable y mono me lo dió en mano.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'Х***а', estrellas:5, fecha:'2025-12-23', pais:'RU', verificada:true, texto:'Aún no lo he usado, pero está bien empaquetado y tiene buena apariencia; veremos cómo funciona en la práctica.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'c***y', estrellas:5, fecha:'2026-05-31', pais:'GB', verificada:true, texto:'Muy bueno, excelente relación calidad-precio' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'o***r', estrellas:5, fecha:'2025-12-08', pais:'IL', verificada:true, texto:'Un producto que vale cada centavo' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'Anónimo', estrellas:5, fecha:'2026-04-21', pais:'PT', verificada:true, texto:'Recomiendo a este vendedor.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'Anónimo', estrellas:5, fecha:'2026-03-11', pais:'BR', verificada:true, texto:'llegó en perfectas condiciones' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'a***r', estrellas:4, fecha:'2026-06-05', pais:'US', verificada:true, texto:'¡Parece genial! ¡Solo lo he usado un par de veces! ¡Me gusta mucho!' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'Z***s', estrellas:5, fecha:'2025-11-09', pais:'ES', verificada:true, texto:'Bastante hidratante, aunque no dura mucho tiempo.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'k***o', estrellas:4, fecha:'2025-10-15', pais:'CL', verificada:true, texto:'llegaron bien, muy buenos' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'b***a', estrellas:4, fecha:'2025-11-10', pais:'ES', verificada:true, texto:'da mucho brillo hidrata mucho' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'S***t', estrellas:5, fecha:'2026-04-01', pais:'US', verificada:true, texto:'Estos productos ayudan a suavizar la piel y, la verdad, me encanta que realmente funcionen.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'D***s', estrellas:5, fecha:'2025-12-07', pais:'CA', verificada:true, texto:'¡Gracias de nuevo, vendedores! ¡Esto es tan hidratante! ! 🌸 🌸' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'A***z', estrellas:5, fecha:'2026-01-07', pais:'ES', verificada:true, texto:'barras super hidratantes es la segunda vez que compro' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'Anónimo', estrellas:5, fecha:'2026-05-05', pais:'BW', verificada:true, texto:'Paquete recibido. Aún no lo he probado, pero tiene muy buena pinta y huele bien. Espero obtener buenos resultados.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'Anónimo', estrellas:5, fecha:'2026-06-11', pais:'FR', verificada:true, texto:'Acabo de probarlo y es un buen bálsamo hidratante. Veremos cómo funciona en unas semanas. Llegó como un par, tal como se describía.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'Anónimo', estrellas:5, fecha:'2026-09-09', pais:'NG', verificada:true, texto:'Estoy muy, muy feliz con el producto, y que Dios bendiga al vendedor por mí, porque ni siquiera esperaba que fuera exactamente lo que vi en la plataforma. Me encanta' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'T***g', estrellas:5, fecha:'2025-11-18', pais:'US', verificada:true, texto:'Huele bien, compré 2 del mismo tamaño. como se muestra en las imágenes. La entrega fue rápida.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'Anónimo', estrellas:5, fecha:'2025-11-02', pais:'IT', verificada:true, texto:'Es un producto realmente muy bueno.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'Anónimo', estrellas:5, fecha:'2026-06-26', pais:'MT', verificada:true, texto:'Estoy satisfecho con esto, gracias. vendedor' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'Anónimo', estrellas:5, fecha:'2026-02-24', pais:'MX', verificada:true, texto:'llegó a tiempo, aún no lo uso pero lo probaré y subiré mi opinión del producto' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'C***y', estrellas:5, fecha:'2026-06-10', pais:'GB', verificada:true, texto:'Bálsamo facial de alta calidad' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'l***l', estrellas:5, fecha:'2026-01-07', pais:'US', verificada:true, texto:'El paquete llegó rápido y en buen estado.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'Anónimo', estrellas:5, fecha:'2026-01-12', pais:'MX', verificada:true, texto:'Llegó bien empaquetado, en buen estado.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'Anónimo', estrellas:4, fecha:'2026-03-29', pais:'MX', verificada:true, texto:'es la primera vez que compro, leí y se oye prometedor, llegaron mis 4 productos, ansiosa por probarlos, muchas gracias Aliexpress y al vendedor' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'Anónimo', estrellas:5, fecha:'2026-01-15', pais:'FR', verificada:true, texto:'Producto tal como se describe. Buena relación calidad-precio.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'J***a', estrellas:5, fecha:'2026-05-10', pais:'ES', verificada:true, texto:'No me llegó nunca pero me devolvieron el dinero pero tengo que decir que el producto es muy bueno ya que otras beses lo e comprado' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'Anónimo', estrellas:5, fecha:'2026-05-27', pais:'CL', verificada:true, texto:'rápido y en buenas condiciones lo probaré para ver que tal' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'E***a', estrellas:4, fecha:'2026-01-04', pais:'BR', verificada:true, texto:'Entrega rápida. Aroma muy agradable. Primera vez comprando.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'S***s', estrellas:5, fecha:'2025-10-15', pais:'AU', verificada:true, texto:'Excelente servicio y entrega.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'Anónimo', estrellas:5, fecha:'2025-09-30', pais:'LT', verificada:true, texto:'Gracias. Llegó en excelentes condiciones.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'Anónimo', estrellas:4, fecha:'2025-10-08', pais:'AU', verificada:true, texto:'El artículo llego bien y rápido a Chile... hidrata bastante...' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'v***s', estrellas:5, fecha:'2026-02-21', pais:'CL', verificada:true, texto:'Fantástico, excelente, potente hidrante.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'Anónimo', estrellas:5, fecha:'2025-12-02', pais:'AU', verificada:true, texto:'Recibido en buen estado. Aún no lo ha probado.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'Anónimo', estrellas:5, fecha:'2026-07-16', pais:'PL', verificada:true, texto:'Llegó con el embalaje dañado, pero está en perfectas condiciones.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'Anónimo', estrellas:5, fecha:'2025-11-14', pais:'CL', verificada:true, texto:'llego en perfecto estado lo probare' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'i***r', estrellas:5, fecha:'2026-03-23', pais:'US', verificada:true, texto:'❤️❤️❤️❤️❤️❤️❤️❤️❤️🥰🥰🥰🥰🥰♥️♥️♥️♥️♥️♥️' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'C***z', estrellas:5, fecha:'2026-01-25', pais:'US', verificada:true, texto:'gracias llego bien el producto' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'C***s', estrellas:5, fecha:'2025-10-30', pais:'US', verificada:true, texto:'Recibido, pero aún no lo he probado. Buen embalaje. Envío rápido.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'Anónimo', estrellas:5, fecha:'2025-10-03', pais:'ES', verificada:true, texto:'Aún no lo he probado, pero se ve muy bien.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'M***a', estrellas:5, fecha:'2026-05-12', pais:'US', verificada:true, texto:'Llego muy rápido,aún no lo e probado.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'E***r', estrellas:5, fecha:'2025-11-21', pais:'ES', verificada:true, texto:'espero k vaya bien, aún no lo probe' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'Anónimo', estrellas:5, fecha:'2026-05-07', pais:'BR', verificada:true, texto:'Aún no lo he usado, pero parece ser bueno.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'Anónimo', estrellas:5, fecha:'2026-09-08', pais:'CO', verificada:true, texto:'Es como en la foto, no lo he probado.' },
  { producto:'Bálsamo de Colágeno VITALIS', nombre:'o***r', estrellas:5, fecha:'2025-11-21', pais:'IL', verificada:true, texto:'¡Vaya, un producto de misiles!' },
];


/* ============================================================
   OPINIONES DEL PRODUCTO · Cabezal de Ducha Masajeadora Spa (29-09-2026)

   167 opiniones REALES de compradores verificados del MISMO modelo que
   enseñan las fotos de la ficha (gris, aro de puntas de silicona, 3 modos,
   filtro; más de 10.000 vendidos), de un total de 966 que tiene publicadas.
   James: "filtra que sean de España, latinas, españolas": 136 de España y el
   resto de países de habla hispana.
   Texto SIN retocar (si hay traducción, la hizo la plataforma). Se cogieron
   las de hasta 320 caracteres en el orden en que salen, buenas y menos
   buenas: 3, 4 y 5 estrellas tal cual. Media real de este conjunto: 4.78.
   10 traen la foto del comprador, bajadas a img/rev/d01-d10.webp (720 px):
   no se enlazan desde la plataforma.
   Mismas reglas que el bálsamo: "opiniones del producto", NUNCA
   "nuestros clientes".
   ============================================================ */
window.RESENAS = (window.RESENAS || []).concat([
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Anónimo", estrellas:5, fecha:'2026-02-15', pais:'ES', verificada:true, foto:'img/rev/d01.webp', texto:"Es muy bueno segundo que pido para mí otro baño ya que tengo poca presión en mi piso y con esto sale el agua bastante bien ,me encanta" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"5***r", estrellas:5, fecha:'2025-10-20', pais:'ES', verificada:true, foto:'img/rev/d02.webp', texto:"No sabía que me iba a encontrar y he quedado realmente satisfecha. Funciona a las mil maravillas. Solo la he probado para ver que funcionaba. Espero que dure mucho." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Anónimo", estrellas:5, fecha:'2026-01-27', pais:'ES', verificada:true, foto:'img/rev/d03.webp', texto:"Todo perfecto" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"a***a", estrellas:5, fecha:'2026-01-19', pais:'ES', verificada:true, foto:'img/rev/d04.webp', texto:"Todo perfecto" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"i***z", estrellas:5, fecha:'2026-04-11', pais:'ES', verificada:true, foto:'img/rev/d05.webp', texto:"Sencillo y con dos morados de chorros y con córrete de agua también, este bueno" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Anónimo", estrellas:4, fecha:'2026-02-17', pais:'ES', verificada:true, foto:'img/rev/d06.webp', texto:"Funciona bien. Muy buena presión, pero tengo la impresión de que se romperá con el primer golpe. Espero que dure." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"s***r", estrellas:5, fecha:'2025-11-22', pais:'ES', verificada:true, foto:'img/rev/d07.webp', texto:"Funciona muy bien." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Anónimo", estrellas:5, fecha:'2026-02-11', pais:'CL', verificada:true, foto:'img/rev/d08.webp', texto:"Parece estar hecho de un material de muy buena calidad y funciona bien." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Anónimo", estrellas:5, fecha:'2026-01-23', pais:'AR', verificada:true, foto:'img/rev/d09.webp', texto:"muy buen producto" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"A***o", estrellas:5, fecha:'2025-10-17', pais:'CL', verificada:true, foto:'img/rev/d10.webp', texto:"llegó súper bien diseño bonito cumple con lo que muestra la foto" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"J***Z", estrellas:5, fecha:'2026-04-01', pais:'ES', verificada:true, texto:"Tiene 3 modos, básicamente 2 , un modo es una mezcla de los 2, pero es sólido, va perfecto. No se puede mas por ese precio." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"J***n", estrellas:5, fecha:'2026-05-05', pais:'ES', verificada:true, texto:"Es el segundo que compro y realmente funciona genial…buena presión y distintos chorros de agua…fácil de montar y la verdad que es bonito…gracias.." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Anónimo", estrellas:5, fecha:'2026-03-18', pais:'ES', verificada:true, texto:"Me ha sorprendido la calidad, muy buen producto. Funciona perfectamente, después de probar he elegido la posición intermedia. Chorros potentes, muy recomendable" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Anónimo", estrellas:5, fecha:'2026-02-27', pais:'ES', verificada:true, texto:"gebial hecha los chorros muy bien con fuerza y entra en la mangera muy bien" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"P***e", estrellas:5, fecha:'2026-03-06', pais:'ES', verificada:true, texto:"Muy satisfecho con la compra, realmente se nota que deja la piel más suave y el pelo más sedoso. Me falta por ver cómo se queda el filtro con el paso del tiempo. de momento me parece muy buena compra y recomendable al 100%." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Anónimo", estrellas:5, fecha:'2026-03-23', pais:'ES', verificada:true, texto:"muy buen producto fiable y cómodo de colocar ahorra aguas y muy cómodo perfecto para el ahorro de agua y práctico" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"F***o", estrellas:5, fecha:'2025-10-07', pais:'ES', verificada:true, texto:"He comprado este modelo y estoy muy satisfecho. Esta bien hecho y los diferentes chorros de agua alegran el rato de ducha." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Anónimo", estrellas:5, fecha:'2025-11-29', pais:'ES', verificada:true, texto:"Muy potente con 2 modos de chorro y filtro. Muy recomendable" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Anónimo", estrellas:5, fecha:'2025-10-08', pais:'ES', verificada:true, texto:"Muy bueno el cabezal de ducha. No pesa nada y tiene un modo de pulverizador muy majo. Encantado ... pediré otros 2" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"A***a", estrellas:5, fecha:'2025-10-07', pais:'ES', verificada:true, texto:"Perfecto, es el tercero de este tipo que compro, este pesa aún menos pero funciona igual de bien!" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Anónimo", estrellas:5, fecha:'2026-06-07', pais:'ES', verificada:true, texto:"tiene mucha presión,ya es el segundo que compro ,está genial" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Anónimo", estrellas:5, fecha:'2025-12-15', pais:'ES', verificada:true, texto:"Consigue la sensación de mayor presión en un grifo que tenemos que no tiene mucha presión. Agradable sensación al ducharse, y adaptable a las conexiones standard de la ducha." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"C***n", estrellas:5, fecha:'2025-11-13', pais:'ES', verificada:true, texto:"muy buen producto,fácil de instalar ,en casa todos contentos" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Anónimo", estrellas:5, fecha:'2026-01-03', pais:'ES', verificada:true, texto:"Ta lo he puesto, y va muy bien. Recomendable" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Anónimo", estrellas:5, fecha:'2025-10-10', pais:'ES', verificada:true, texto:"muy bueno artículo, se nota el buen material de fabricación, aparenta ser duradero y comodo para usarlo. !" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"f***r", estrellas:5, fecha:'2025-11-24', pais:'ES', verificada:true, texto:"Producto correcto,todo perfecto. Recomendable al 100% tienda y vendedor profesional. Gracias" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"A***z", estrellas:5, fecha:'2026-02-19', pais:'ES', verificada:true, texto:"funciona muy bien tiene mucha fuerza con el agua muy contento con la compra recomiendo la compra del producto" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"L***z", estrellas:5, fecha:'2025-12-07', pais:'ES', verificada:true, texto:"el producto,muy bien,muy contenta,,recomendadisimo.." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Anónimo", estrellas:5, fecha:'2025-12-09', pais:'ES', verificada:true, texto:"Se le ve muy buena calidad y la manera de controlar como sale el agua, me gusta mucho tanto el aspecto como la utilidad" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"m***m", estrellas:5, fecha:'2025-10-13', pais:'ES', verificada:true, texto:"Es un buen cabezal de ducha pero no se le pueden poner filtros para mejorar la calidad del agua, precio y estética muy recomendables" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Anónimo", estrellas:5, fecha:'2026-05-26', pais:'ES', verificada:true, texto:"todo perfecto, muy recomendable" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Anónimo", estrellas:5, fecha:'2026-03-19', pais:'ES', verificada:true, texto:"por ahora genial. no puedo abrir el grifo del todo de la presión que saca" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"A***a", estrellas:5, fecha:'2025-10-17', pais:'ES', verificada:true, texto:"Parece de buena calidad y el agua sale con fuerza. Nos gusta mucho." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"M***d", estrellas:5, fecha:'2026-02-19', pais:'ES', verificada:true, texto:"Muy recomendable" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"j***a", estrellas:5, fecha:'2025-12-17', pais:'ES', verificada:true, texto:"Esta bastante bien, la goma un poco dura pero en general bien" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"O***n", estrellas:5, fecha:'2025-10-17', pais:'ES', verificada:true, texto:"LA DESCRIPCIÓN COINCIDE CON LA DETALLADA EN LA PAGINA ES ESPECTACULAR." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Anónimo", estrellas:5, fecha:'2026-05-02', pais:'ES', verificada:true, texto:"relación precio calidad. bien tal cual a la imagen, me gusta" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"J***s", estrellas:5, fecha:'2025-11-12', pais:'ES', verificada:true, texto:"Perfecto. Envío rápido. Cuando lo pruebe pondré valoraciones." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Anónimo", estrellas:5, fecha:'2026-03-11', pais:'ES', verificada:true, texto:"muy practico, buen material, fácil de montar,llego rápido y bien envalado" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"C***e", estrellas:5, fecha:'2025-12-31', pais:'ES', verificada:true, texto:"Muy contento con el producto, ya lo he probado y está durando bien, lo recomiendo." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Anónimo", estrellas:5, fecha:'2025-12-09', pais:'ES', verificada:true, texto:"Se le ve muy buena calidad y la manera de controlar como sale el agua, me gusta mucho tanto el aspecto como la utilidad" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Anónimo", estrellas:5, fecha:'2026-03-25', pais:'ES', verificada:true, texto:"Estupendo, multiplica la presión y funciona perfectamente" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Anónimo", estrellas:5, fecha:'2026-03-31', pais:'ES', verificada:true, texto:"Por el precio que tiene merece la pena cambiar el cabezal de la ducha. No lo he probado pero me da la sensación que debe resultar muy agradable ducharte con diferentes chorros de agua." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Anónimo", estrellas:5, fecha:'2026-03-06', pais:'ES', verificada:true, texto:"Todo perfecto, lo he probado y de momento la presión es buena" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Anónimo", estrellas:5, fecha:'2026-04-13', pais:'ES', verificada:true, texto:"Fiel a la descripción. Parece de buena calidad por su precio" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"S***k", estrellas:5, fecha:'2026-02-14', pais:'ES', verificada:true, texto:"Me ha gustado mucho y volvería a comprarlo seguro!. Me ha encantado!!" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Anónimo", estrellas:4, fecha:'2026-02-28', pais:'ES', verificada:true, texto:"el material es plástico, pero lo he probado y el agua sale de tres maneras posibles. Así que por esa parte muy bien. Falla que es de plástico, no sé lo que durará." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"M***o", estrellas:5, fecha:'2025-12-03', pais:'ES', verificada:true, texto:"super bien el mando de ducha...buena presion y varios tipos de caños..." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Anónimo", estrellas:5, fecha:'2026-03-24', pais:'ES', verificada:true, texto:"por el precio que tiene se ve muy bien, lo he probado y funciona bien" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"S***k", estrellas:5, fecha:'2026-02-14', pais:'ES', verificada:true, texto:"Me ha gustado mucho y volvería a comprarlo seguro!. Me ha encantado!!" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"E***m", estrellas:4, fecha:'2026-01-01', pais:'ES', verificada:true, texto:"Es como indican en fotos, tengo que probar que tal va. Llego con una raspadura/golpe pero no daña el funcionamiento. Llegó más rápido de lo previsto 👍" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Anónimo", estrellas:5, fecha:'2026-02-14', pais:'ES', verificada:true, texto:"Tal como se describe. Buen producto." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"J***a", estrellas:5, fecha:'2025-10-10', pais:'ES', verificada:true, texto:"todo perfecto gracias" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"J***a", estrellas:5, fecha:'2026-01-22', pais:'ES', verificada:true, texto:"super buenísimo lo recomiendo" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"c***s", estrellas:5, fecha:'2026-02-27', pais:'ES', verificada:true, texto:"si que da más presión! perfecto!" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"j***z", estrellas:5, fecha:'2025-12-15', pais:'ES', verificada:true, texto:"muy bueno y fácil de usar potencia de agua" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Anónimo", estrellas:5, fecha:'2025-11-20', pais:'ES', verificada:true, texto:"Perfecto y entrega super rápida !!!" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"s***z", estrellas:5, fecha:'2026-02-07', pais:'ES', verificada:true, texto:"muy bien producto a un muy buen precio" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"D***a", estrellas:5, fecha:'2025-10-20', pais:'ES', verificada:true, texto:"todo perfecto y de buena calidad" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"f***f", estrellas:5, fecha:'2025-10-08', pais:'ES', verificada:true, texto:"Bonita, práctica, liviana." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Anónimo", estrellas:5, fecha:'2026-01-08', pais:'ES', verificada:true, texto:"Muy buena alcachofa, sale con potencia el agua" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Anónimo", estrellas:5, fecha:'2026-06-02', pais:'ES', verificada:true, texto:"Perfecto y enviado en una semana. Satisfecho." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Anónimo", estrellas:5, fecha:'2026-03-18', pais:'ES', verificada:true, texto:"De momento perfecto y con mucha fuerza" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"h***z", estrellas:5, fecha:'2026-01-22', pais:'ES', verificada:true, texto:"buena calidad" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"E***l", estrellas:5, fecha:'2026-01-17', pais:'ES', verificada:true, texto:"Bastante adecuado" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"D***o", estrellas:5, fecha:'2026-01-27', pais:'ES', verificada:true, texto:"Funciona a la perfección" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"J***o", estrellas:5, fecha:'2026-04-01', pais:'ES', verificada:true, texto:"Funciona muy bien" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Anónimo", estrellas:5, fecha:'2026-04-10', pais:'ES', verificada:true, texto:"Me ha encantado" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"a***o", estrellas:5, fecha:'2025-12-27', pais:'ES', verificada:true, texto:"funciona muy bien" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"a***r", estrellas:5, fecha:'2026-01-14', pais:'ES', verificada:true, texto:"De momento muy bien" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"c***e", estrellas:5, fecha:'2026-01-10', pais:'ES', verificada:true, texto:"está muy chulo!!!" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Anónimo", estrellas:5, fecha:'2026-06-08', pais:'ES', verificada:true, texto:"muy bueno y útil" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"P***R", estrellas:5, fecha:'2026-06-27', pais:'ES', verificada:true, texto:"Super bien muy satisfecha" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Anónimo", estrellas:5, fecha:'2026-06-28', pais:'ES', verificada:true, texto:"perfecto gracias" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"S***a", estrellas:5, fecha:'2025-10-30', pais:'ES', verificada:true, texto:"tiene buena presión de agua." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"L***i", estrellas:5, fecha:'2025-10-11', pais:'ES', verificada:true, texto:"es plástico, pero funciona muy bien" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"T***Z", estrellas:4, fecha:'2026-02-23', pais:'ES', verificada:true, texto:"Funciona muy bien, perfecto" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"F***r", estrellas:4, fecha:'2025-12-15', pais:'ES', verificada:true, texto:"un poco pesado pero va bien" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"E***r", estrellas:4, fecha:'2026-04-13', pais:'ES', verificada:true, texto:"Hace perfectamente su función." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"D***o", estrellas:4, fecha:'2025-12-29', pais:'ES', verificada:true, texto:"Muy buen producto, este es el segundo que he pedido." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Anónimo", estrellas:4, fecha:'2025-10-13', pais:'ES', verificada:true, texto:"bien para el precio q tiene, si se nota mas fuerza de agua" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Anónimo", estrellas:4, fecha:'2026-02-15', pais:'ES', verificada:true, texto:"Muy bien el producto pero podría al menos vir con un filtro incluído." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"M***N", estrellas:4, fecha:'2025-10-04', pais:'ES', verificada:true, texto:"Esta muy bien" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"S***o", estrellas:4, fecha:'2026-02-01', pais:'ES', verificada:true, texto:"Muy bien precio calidad" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"S***a", estrellas:5, fecha:'2025-12-05', pais:'ES', verificada:true, texto:"me ha llegado bien en los pedidos múltiples buen vendedor, es de plástico,no lo he probado todavía" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"j***z", estrellas:5, fecha:'2025-12-05', pais:'ES', verificada:true, texto:"Muy bueno con mucha potencia de agua y casi pulverizada" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Anónimo", estrellas:5, fecha:'2026-03-25', pais:'ES', verificada:true, texto:"Buena calidad y precio, envío rápido, aún no lo he probado, pero tiene buena pinta." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Anónimo", estrellas:5, fecha:'2026-03-25', pais:'ES', verificada:true, texto:"Buena calidad y precio, envío rápido, aún no lo he probado, pero tiene buena pinta." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Anónimo", estrellas:4, fecha:'2025-11-19', pais:'ES', verificada:true, texto:"todo perfecto funciona muy bien genial ahorra mucka agua" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"P***a", estrellas:5, fecha:'2026-01-10', pais:'ES', verificada:true, texto:"tengo una puesta en casa y he cogido otra por si acaso. funciona bien" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"F***S", estrellas:5, fecha:'2025-10-27', pais:'ES', verificada:true, texto:"Es deliciosa la ducha con el pulverizador. Gracias." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"F***O", estrellas:5, fecha:'2026-02-14', pais:'ES', verificada:true, texto:"Buen producto, buen precio, todo está correcto excepto el embalaje, que está mal protegido." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"F***S", estrellas:5, fecha:'2026-01-08', pais:'ES', verificada:true, texto:"Excelente producto. Funciona perfectamente. Envío muy rápido." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"I***o", estrellas:5, fecha:'2025-10-03', pais:'ES', verificada:true, texto:"lllegp rápido todo bien" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"d***a", estrellas:5, fecha:'2026-01-20', pais:'ES', verificada:true, texto:"bueno artículo" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"j***z", estrellas:5, fecha:'2026-02-26', pais:'ES', verificada:true, texto:"Bueno, bonito y barato, funciona" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Anónimo", estrellas:5, fecha:'2025-10-19', pais:'ES', verificada:true, texto:"De momento perfecto. Veremos lo que dura." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"M***z", estrellas:5, fecha:'2026-02-08', pais:'ES', verificada:true, texto:"FUNCIONA BIEN" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"c***n", estrellas:5, fecha:'2025-10-07', pais:'ES', verificada:true, texto:"hace su trabajo, gracias" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"P***R", estrellas:5, fecha:'2026-02-12', pais:'ES', verificada:true, texto:"Estupendo tal cual" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"P***9", estrellas:5, fecha:'2026-01-15', pais:'ES', verificada:true, texto:"Buen producto" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Anónimo", estrellas:5, fecha:'2026-01-21', pais:'ES', verificada:true, texto:"Buen articulo." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Anónimo", estrellas:5, fecha:'2026-01-21', pais:'ES', verificada:true, texto:"Buen articulo." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"a***r", estrellas:5, fecha:'2026-01-07', pais:'ES', verificada:true, texto:"me encanta ,va genial" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Anónimo", estrellas:5, fecha:'2026-02-12', pais:'ES', verificada:true, texto:"perfecto gracias 🫂" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Anónimo", estrellas:5, fecha:'2026-01-27', pais:'ES', verificada:true, texto:"muy buena pinta" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"M***s", estrellas:5, fecha:'2025-12-11', pais:'ES', verificada:true, texto:"Funciona bien" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"C***o", estrellas:4, fecha:'2025-12-10', pais:'ES', verificada:true, texto:"Parece ke cumple sus funciones, veremos hasta kuando, de momento bien" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"E***r", estrellas:4, fecha:'2025-10-13', pais:'ES', verificada:true, texto:"Funciona bien, cumple con la descripción y con las expectativas" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"A***n", estrellas:4, fecha:'2025-11-16', pais:'ES', verificada:true, texto:"está muí bien por el precio" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"C***o", estrellas:4, fecha:'2025-12-10', pais:'ES', verificada:true, texto:"Parece ke cumple sus funciones, veremos hasta kuando, de momento bien" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"E***r", estrellas:4, fecha:'2025-10-13', pais:'ES', verificada:true, texto:"Funciona bien, cumple con la descripción y con las expectativas" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"A***n", estrellas:4, fecha:'2025-11-16', pais:'ES', verificada:true, texto:"está muí bien por el precio" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"E***r", estrellas:5, fecha:'2025-12-11', pais:'ES', verificada:true, texto:"Se ve genial,,ya lo probare" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Anónimo", estrellas:5, fecha:'2025-11-09', pais:'ES', verificada:true, texto:"Todo está bien." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Anónimo", estrellas:5, fecha:'2025-11-09', pais:'ES', verificada:true, texto:"Todo está bien." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Anónimo", estrellas:4, fecha:'2026-02-14', pais:'ES', verificada:true, texto:"barato. vale para lo que sirve" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"d***o", estrellas:4, fecha:'2026-01-22', pais:'ES', verificada:true, texto:"va muy bien ,esperemos que sea duradero" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"a***a", estrellas:4, fecha:'2026-02-26', pais:'ES', verificada:true, texto:"muy bonito y va muy bien" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"C***a", estrellas:4, fecha:'2025-10-18', pais:'ES', verificada:true, texto:"buen producto y rrapido" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"c***z", estrellas:5, fecha:'2026-02-10', pais:'ES', verificada:true, texto:"muy bien probado satisfactoriamente" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"J***n", estrellas:5, fecha:'2025-12-28', pais:'ES', verificada:true, texto:"Se ve bien fabricado y de buenos materiales." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"m***o", estrellas:5, fecha:'2025-10-04', pais:'ES', verificada:true, texto:"Este cabezal de ducha es magnífico, es una pena que se rompa tan rápido." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Anónimo", estrellas:5, fecha:'2026-02-12', pais:'ES', verificada:true, texto:"va estupendo, a ver cuánto dura! espero que mucho!" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"E***a", estrellas:5, fecha:'2026-01-06', pais:'ES', verificada:true, texto:"buen articulo espero k valla bien" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"f***a", estrellas:5, fecha:'2026-02-10', pais:'ES', verificada:true, texto:"Está genial! Pero pensaba que tenía más presión" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Anónimo", estrellas:5, fecha:'2026-04-03', pais:'ES', verificada:true, texto:"Muy buena pinta" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"c***a", estrellas:5, fecha:'2026-02-22', pais:'ES', verificada:true, texto:"se aclopa bien" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Anónimo", estrellas:5, fecha:'2026-02-10', pais:'ES', verificada:true, texto:"Tengo que probarlo." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"J***z", estrellas:5, fecha:'2026-01-23', pais:'ES', verificada:true, texto:"Todo bien. Correcto. OK." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Anónimo", estrellas:5, fecha:'2025-10-06', pais:'ES', verificada:true, texto:"todo okey y todo correcto" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"J***z", estrellas:4, fecha:'2025-11-15', pais:'ES', verificada:true, texto:"Bastante bueno. Funciona bien" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"c***s", estrellas:3, fecha:'2026-02-25', pais:'ES', verificada:true, texto:"buen duchero, con dos opciones de agua y botón parada" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Anónimo", estrellas:5, fecha:'2026-01-04', pais:'ES', verificada:true, texto:"ok 👍 🆗️ 👌." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"E***r", estrellas:3, fecha:'2026-02-24', pais:'ES', verificada:true, texto:"No está mal. Esperaba más." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Y***v", estrellas:3, fecha:'2026-02-10', pais:'ES', verificada:true, texto:"No está mal, haces su función" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Anónimo", estrellas:5, fecha:'2026-02-11', pais:'ES', verificada:true, texto:"Perfecto, todo está bien." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"d***z", estrellas:3, fecha:'2025-12-13', pais:'ES', verificada:true, texto:"Muy plástico. Lo bueno es que es desmontable para limpieza" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"D***a", estrellas:3, fecha:'2026-02-10', pais:'ES', verificada:true, texto:"El producto ha llegado bien y a tiempo. La calidad es aceptable pero tendría que mejorar para que pueda recibir las 5 estrellas." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Anónimo", estrellas:5, fecha:'2025-10-11', pais:'CL', verificada:true, texto:"A primera vista se siente liviano y de cerca detalles pobres de baja calidad pero funciona tal cual se indica con sus 3 modos, la potencia es increíble y el chorro es agradable de sentir, toca probar si sirve el filtro para la piel. Recomiendo!" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Anónimo", estrellas:5, fecha:'2026-03-13', pais:'CL', verificada:true, texto:"me gustó mucho ya que tiene tres modos y también se puede regular la presión del agua lo recomiendo" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"V***z", estrellas:5, fecha:'2025-10-28', pais:'CL', verificada:true, texto:"Bien, producto llega en buenas condiciones, se ve que es de buen material y al parecer hará su trabajo. Vendedor envió el producto comprado, demora 10 días en llegar a mis manos, vendedor responsable cumple. Dicho lo anterior, queda recomendado 100% a la Comunidad de Aliexpress. Saludos cordiales desde Chile." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"D***a", estrellas:5, fecha:'2025-10-03', pais:'CL', verificada:true, texto:"Funciona perfecto y viene con filtro, es el tercero que compro." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"L***z", estrellas:5, fecha:'2025-10-11', pais:'CL', verificada:true, texto:"muy muy buena calidad tal cual sus especificaciones lo mejor es la presión del agua" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"m***i", estrellas:5, fecha:'2025-10-30', pais:'CL', verificada:true, texto:"buena calidad en relación con su precio ,llego una semana antes de lo presupuestado,es segunda vez que compro esta vez fue para mis papas" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"C***a", estrellas:5, fecha:'2025-10-03', pais:'CL', verificada:true, texto:"Se ve bien el material, y llegó rápido." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"F***s", estrellas:5, fecha:'2025-09-30', pais:'CL', verificada:true, texto:"Una ducha espectacular Muy conforme con la compra" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Anónimo", estrellas:4, fecha:'2025-10-11', pais:'CL', verificada:true, texto:"El artículo corresponde a la descripción, muy satisfecho con la compra, llegó antes del tiempo indicado, recomiendo al vendedor." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Anónimo", estrellas:5, fecha:'2025-11-29', pais:'MX', verificada:true, texto:"del pedido fue lo mejor, tal cómo lo pedí" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Anónimo", estrellas:5, fecha:'2025-10-13', pais:'CO', verificada:true, texto:"Excelente ducha, en relación al precio es mejor de lo esperado." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Anónimo", estrellas:5, fecha:'2025-10-14', pais:'CL', verificada:true, texto:"buena igual que la imagen muy útil .." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"G***s", estrellas:5, fecha:'2025-10-14', pais:'CL', verificada:true, texto:"Lo probé y es excelente, gracias." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Anónimo", estrellas:5, fecha:'2026-02-28', pais:'CL', verificada:true, texto:"excelente producto y muy facil de manipular" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Anónimo", estrellas:5, fecha:'2026-03-17', pais:'CL', verificada:true, texto:"llego todo bien, funciona perfecto" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"M***Z", estrellas:5, fecha:'2026-01-09', pais:'CL', verificada:true, texto:"Buen producto, altamente recomendado." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"R***a", estrellas:5, fecha:'2026-03-02', pais:'PE', verificada:true, texto:"Excelente cabezal, cumple su función." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Anónimo", estrellas:5, fecha:'2026-02-07', pais:'CO', verificada:true, texto:"aún no se ha probado pero los materiales se ven bien, de buena calidad" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"F***z", estrellas:5, fecha:'2025-12-31', pais:'PY', verificada:true, texto:"¡Producto excelente!" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"J***a", estrellas:5, fecha:'2026-01-27', pais:'CO', verificada:true, texto:"Producto excelente" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Anónimo", estrellas:5, fecha:'2026-03-11', pais:'CL', verificada:true, texto:"Genial, me encantó." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"A***a", estrellas:5, fecha:'2026-02-22', pais:'CL', verificada:true, texto:"funciona muy bien" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"J***z", estrellas:5, fecha:'2026-02-18', pais:'CL', verificada:true, texto:"Funciona de maravilla." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"A***r", estrellas:5, fecha:'2025-12-09', pais:'AR', verificada:true, texto:"Todo bien. Tal cual la decripcion y sus funciones." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Anónimo", estrellas:5, fecha:'2025-10-04', pais:'CL', verificada:true, texto:"buen producto en relacion precio y calidad" },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Anónimo", estrellas:3, fecha:'2026-04-13', pais:'CL', verificada:true, texto:"Excelente producto, me encantó." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Anónimo", estrellas:4, fecha:'2026-02-23', pais:'MX', verificada:true, texto:"Productos en envío combinado con Choice, son más seguros en su transporte y entrega, con Choice nunca he tenido inconveniente con su entrega ni con daños de ningún tipo." },
  { producto:'Cabezal de Ducha Masajeadora Spa', nombre:"Anónimo", estrellas:5, fecha:'2026-03-17', pais:'CL', verificada:true, texto:"me gustó el micrófono. genera fuerza al bañarse. se nota un poco que es de platico pero vale la pena" },
]);
